// Flat ESLint config for all TypeScript in the workspace.
// Generated code and build output are never linted.
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/build/**",
      "**/generated/**",
      "**/*.gen.*",
      "**/node_modules/**",
      "**/.turbo/**",
      // Local tool scratch that is gitignored but NOT thereby hidden from
      // eslint: flat config does not read .gitignore. Both of these are
      // generated by running dev tooling, so they exist only on a developer's
      // machine — which is why CI stayed green while `make lint` went red for
      // anyone who had run the dev server or the playground.
      //
      // .vite — Vite's dependency pre-bundle cache. Normally lands in
      // node_modules/.vite, but Vite falls back to <root>/.vite when the dev
      // server is started from inside an app directory.
      "**/.vite/**",
      // chat_playground — generated app source from playground runs
      // (services/agents), not repo code.
      "**/chat_playground/**",
      // Playground project homes: generated app source, not repo code.
      "playground/.projects/**",
      "playground/.devtools/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
);
