/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
} from "react";
import {
  Avatar,
  AvatarGroup,
  Box,
  Button,
  Chip,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Divider,
  IconButton,
  Stack,
  Tooltip,
  Typography,
} from "@wso2/oxygen-ui";
import {
  ExternalLink,
  Sparkles,
  SquarePen,
  X as XIcon,
} from "@wso2/oxygen-ui-icons-react";
import { useNavigate } from "@tanstack/react-router";
import { useStickToBottom } from "use-stick-to-bottom";
import { useAgentChat } from "../useAgentChat";
import {
  chatKeyFor,
  consumePendingSeed,
  peekPendingSeed,
  subscribeSeed,
} from "../chatStore";
import { useTurnEndDependencyRefresh } from "../useTurnEndDependencyRefresh";
import { useAgentEngaged } from "../useAgentEngaged";
import { useCurrentAuthor } from "../currentUser";
import { buildFeed, participantsOf, type FeedBlock } from "../feed";
import { answerableQuestionIds } from "../questionCards";
import { MessageList } from "./MessageList";
import { ChatInput } from "./ChatInput";
import { DESIGN_COMMAND } from "@aep/contracts/commands";

// Default a touch wider than the old 380 so the activity rail + narration
// breathe; the user can drag-resize and the choice persists.
const AGENT_CHAT_PANEL_WIDTH = 440;
const MIN_WIDTH = 360;
const MAX_WIDTH = 720;
const WIDTH_STEP = 24; // keyboard resize increment
const WIDTH_KEY = "aep.chat.panelWidth";

// Empty-state starter prompts — one click prefills the composer (mirrors
// ProjectCreate's example-prompt pattern, scaled to a chip).
/**
 * The empty state is reachable only after **New conversation** (#522 fires the
 * kickoff at project creation, so the first transcript is never empty), which
 * means the project already HAS a spec by the time anyone reads this. The
 * suggestions therefore open a conversation ABOUT that spec rather than offer
 * to draft one.
 */
const SUGGESTIONS = [
  "What's still assumed in this spec?",
  "Add a feature to this project",
  "Walk me through the design",
] as const;

const clampWidth = (n: number): number =>
  Math.min(MAX_WIDTH, Math.max(MIN_WIDTH, Math.round(n)));

function initialOf(name: string): string {
  return name.trim().charAt(0).toUpperCase() || "?";
}

// The project AI panel (#130), reworked into a multi-user activity stream
// (task 3): the header, scroll region, and composer live here; feed rendering
// and the turn/step split live in their own components.
export function AgentChatPanel({
  org,
  projectName,
  displayName,
  onClose,
  autoGenerate,
  onAutoGenerated,
  specWorkspace = true,
}: {
  org: string;
  projectName: string;
  displayName?: string | undefined;
  onClose: () => void;
  /** Generate-design CTA (#159): auto-send the design turn once, derived from
   *  the current requirements. The requirements half of this signal is gone —
   *  the platform fires `/start` itself at project creation (#562), and the one
   *  CTA that still starts an interview seeds the composer directly. */
  autoGenerate?: "design";
  /** Called after the auto-send fires, so the caller can clear the signal. */
  onAutoGenerated?: () => void;
  /**
   * Spec-room chat (default): StartTurn joins collab and "Open spec" /
   * question pills navigate to `/projects/$projectName/spec`.
   * Off for Marketplace register — that synthetic project has no spec room.
   */
  specWorkspace?: boolean;
}) {
  const {
    messages,
    isSending,
    activeTurnId,
    conversationReady,
    conversationError,
    historyReady,
    send,
    newConversation,
  } = useAgentChat(org, projectName, { collab: specWorkspace });
  const chatKey = chatKeyFor(org, projectName);
  const author = useCurrentAuthor();
  const navigate = useNavigate();
  const [draft, setDraft] = useState("");
  // Files attached to the message being composed (#428). Held here, beside the
  // draft, because they share its lifecycle exactly: both clear on an accepted
  // send and both SURVIVE a refused one. The bytes exist nowhere but this array
  // (ADR-0019), so dropping them on a routine 409 would cost the user a re-pick
  // of every file from disk.
  const [attachedFiles, setAttachedFiles] = useState<File[]>([]);

  const feed = useMemo(
    () => buildFeed(messages, { currentUserId: author.id, activeTurnId }),
    [messages, author.id, activeTurnId],
  );
  const participants = useMemo(
    () => participantsOf(messages, author.id),
    [messages, author.id],
  );
  // A question is live only while unanswered and not superseded by a later
  // delivered user message. One O(n) pass per log change.
  const answerableIds = useMemo(() => answerableQuestionIds(messages), [messages]);

  const awaiting = !isSending && answerableIds.size > 0;

  // A teammate's running turn locks the composer (a concurrent send 409s
  // anyway — this makes the lock legible rather than surprising).
  const runningTurn = feed.find(
    (b): b is Extract<FeedBlock, { kind: "turn" }> =>
      b.kind === "turn" && b.status === "running",
  );
  const teammateRunning =
    runningTurn && !runningTurn.attribution.isOwn
      ? runningTurn.attribution.displayName
      : null;
  // `!conversationReady` covers the brief window before the project's shared
  // thread id resolves (#430) — a send then would have nowhere to go.
  const inputDisabled = isSending || Boolean(teammateRunning) || !conversationReady;
  // The resolve-failed hint says WHY the composer is disabled — without it a
  // failed thread resolve reads as a dead panel. Recovery is automatic (the
  // query refetches on window focus), so the wording promises the retry.
  const hint = conversationError
    ? "Couldn't reach the project conversation — it will retry when you return to this tab."
    : teammateRunning
      ? `Agent is working on ${teammateRunning}'s request…`
      : awaiting
        ? "Answer the agent's questions on the spec view, or type a reply…"
        : null;
  // Before a turn has emitted anything it has no block yet — show a tail
  // "Working…" so a send never looks dropped.
  //
  // Derived from the LOG as well as this panel's own composer state: an aimed
  // send (#666) dispatches through its own hook, so `isSending` here never
  // flips for it — and its message sat in the feed for the whole dispatch-plus-
  // first-token window with nothing pulsing, reading as dropped. The log
  // already carries the signal: an optimistic user row is `in_flight` until
  // the turn's history replaces it, which is the same fact `isSending` proxies.
  const sendInFlight =
    isSending || messages.some((m) => m.role === "user" && m.status === "in_flight");
  const showWorkingTail =
    sendInFlight && !feed.some((b) => b.kind === "turn" && b.status === "running");

  // Same-file tool runs render collapsed by default; a click flips membership.
  const [expandedGroups, setExpandedGroups] = useState<Set<string>>(() => new Set());
  const toggleGroup = useCallback((id: string) => {
    setExpandedGroups((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  // Follow the streaming tail (breaks the lock if the user scrolls up).
  const { scrollRef, contentRef } = useStickToBottom();

  const openSpec = useCallback(() => {
    if (!specWorkspace) return;
    void navigate({
      to: "/projects/$projectName/spec",
      params: { projectName },
    });
  }, [navigate, projectName, specWorkspace]);

  // A question arriving does NOT move the user (#522/#562): the chat is the
  // spine, and a blocking question does not earn the right to take the
  // viewport. The panel says one has arrived — `QuestionsPointer` in TurnBlock,
  // "The agent has N questions → Answer them" — and the CLICK is what
  // navigates. Whoever is deep in the Builds page when a teammate's interview
  // reaches a round keeps their place.
  //
  // This replaced an effect that called `openSpec()` the moment an unanswered
  // question appeared, deduped by toolCallId in a module-level Set. It was
  // written before the kickoff fired at creation, when the only way to reach a
  // question was to have asked for one; now every project's first minute
  // produces one, so it yanked every new user off the page they had just
  // landed on.

  // --- Drag-to-resize (persisted) --------------------------------------
  const [width, setWidth] = useState<number>(() => {
    try {
      const raw = localStorage.getItem(WIDTH_KEY);
      const n = raw ? Number.parseInt(raw, 10) : Number.NaN;
      if (Number.isFinite(n)) return clampWidth(n);
    } catch {
      // fall through to default
    }
    return AGENT_CHAT_PANEL_WIDTH;
  });
  const [dragging, setDragging] = useState(false);
  const dragRef = useRef<{ startX: number; startW: number } | null>(null);
  useEffect(() => {
    if (!dragging) return;
    const onMove = (e: MouseEvent) => {
      const d = dragRef.current;
      if (d) setWidth(clampWidth(d.startW + (d.startX - e.clientX)));
    };
    const onUp = () => setDragging(false);
    window.addEventListener("mousemove", onMove);
    window.addEventListener("mouseup", onUp);
    return () => {
      window.removeEventListener("mousemove", onMove);
      window.removeEventListener("mouseup", onUp);
    };
  }, [dragging]);
  useEffect(() => {
    try {
      localStorage.setItem(WIDTH_KEY, String(width));
    } catch {
      // width persistence is best-effort
    }
  }, [width]);

  // --- One-shot generate (#159 design) ---------------------------------
  // Fire exactly once per signal, re-arm on clear so a later Generate click
  // fires again. `send` is held in a ref and kept out of the deps: its identity
  // flips whenever `isSending` changes, which would otherwise re-run this
  // mid-turn. See the original panel note (#150) for the full rationale.
  const sendRef = useRef(send);
  sendRef.current = send;
  // The backstop on injected commands. The overview's stage already declines to
  // attach `?generate` while the agent is mid-exchange, but the signal also
  // arrives from a pasted or bookmarked URL — and this is where "may I send
  // this" is actually decided, so it is decided once, for both signals.
  // Held in a ref for the same reason `send` is: it flips as the turn runs, and
  // as a dependency it would re-run this effect mid-turn.
  const engaged = useAgentEngaged(org, projectName);
  const engagedRef = useRef(engaged);
  engagedRef.current = engaged;
  const autoGenFiredRef = useRef(false);
  useEffect(() => {
    if (!autoGenerate) {
      autoGenFiredRef.current = false;
      return;
    }
    // Hold — do not consume — until the project's thread id resolves (#430):
    // `send` no-ops without it, so consuming now would swallow the click
    // silently. The panel mounts fresh on the Generate CTA (Collapse
    // unmountOnExit), so a cold cache makes this window the COMMON case, not
    // an edge. `conversationReady` is a dep: the flip re-runs this and fires.
    if (!conversationReady) return;
    if (autoGenFiredRef.current) return;
    autoGenFiredRef.current = true;
    // A suppressed generate is CONSUMED, not deferred: the param is cleared
    // exactly as a sent one clears it. Leaving it in the URL would fire the
    // command on a later mount — once the question is answered and the guard
    // opens — and a send with no click behind it is worse than the bug this
    // guards, because nothing on screen would explain it.
    if (!engagedRef.current) {
      // Flow commands go VERBATIM: aep-api classifies every /<skill> token and
      // the agents service composes the wording and picks the flow's eager
      // skills, so this CTA and a typed command produce identical turns.
      sendRef.current(DESIGN_COMMAND);
    }
    onAutoGenerated?.();
  }, [autoGenerate, conversationReady, onAutoGenerated]);

  // Seeded turn (#252 Task 5, "Resolve via chat"): the dep card / drawer /
  // build drawer (Task 9) writes a message into chatStore's pendingSeed slot
  // from a subtree that doesn't share this component's tree — consumed here
  // exactly once, mirroring autoGenerate's one-shot shape above but sourced
  // from the store since the content is per-click dynamic, not a fixed enum.
  // `consumePendingSeed` is get-and-clear: calling it fresh at effect-run time
  // (rather than trusting the closed-over `pendingSeed` value) makes a
  // StrictMode double-invoke a no-op on its second pass, since the seed is
  // already gone from the store by then.
  const pendingSeed = useSyncExternalStore(
    useCallback((fn: () => void) => subscribeSeed(chatKey, fn), [chatKey]),
    () => peekPendingSeed(chatKey),
  );
  useEffect(() => {
    // Hold until the thread id resolves, same as autoGenerate above: the
    // worst seed to swallow is a member's SUBMITTED INTERVIEW ANSWERS — the
    // form has already closed for the whole room by the time the seed is
    // written, so a dropped send here loses them with nothing on screen.
    if (!pendingSeed || !conversationReady) return;
    // A GUARDED seed additionally waits for the server's history. The backstop
    // below exists to see an exchange this browser did not take part in, and
    // until the rehydrate lands the log is empty — so checking it any earlier
    // asks a question whose answer is always "nothing is happening". A seed
    // carrying the user's OWN words never waits: theirs is the copy that would
    // be lost.
    if (pendingSeed.guarded && !historyReady) return;
    const seed = consumePendingSeed(chatKey);
    if (!seed) return; // already consumed (StrictMode re-invoke, or a race)
    // The backstop on INJECTED commands, and the reason it lives here rather
    // than at the click: the surface that offers one (the overview's spec card)
    // decides from the LOCAL chat log, which does not exist until this panel
    // has mounted and rehydrated. A teammate opening the overview in a fresh
    // browser sees an empty log and a card that reads "nothing has started",
    // while the server thread holds someone else's unanswered question — and
    // the injected `/start` would answer it with the agent's own defaults.
    // By the time the seed reaches this effect the rehydrate has run, so this
    // is the first moment anyone can actually tell. Consumed either way: a
    // deferred command is worse than a dropped one, since it would fire later
    // with no click behind it.
    if (seed.guarded && engagedRef.current) return;
    sendRef.current(seed.message);
  }, [pendingSeed, conversationReady, historyReady, chatKey]);

  // Turn-end freshness fallback (#252 Task 5) — always on, so it fires even
  // when the chat is used away from the Spec view (SpecView's useTurnEndFlush
  // additionally closes the race deterministically whenever it's mounted and
  // the room is connected).
  useTurnEndDependencyRefresh(chatKey, projectName);

  const submit = () => {
    if (!draft.trim() || inputDisabled) return;
    // Everything goes VERBATIM — including `/<skill> [text]` shortcuts (e.g.
    // /start, /design): the SERVER classifies every command token and enriches
    // /start with the captured idea; the agents service owns the wording and
    // the flow's eager skills. Unknown skills surface as the agent's loadSkill
    // not-found (client-side validation is parked, #325).
    //
    // Attachments ride whatever was typed — the composer does not inspect it, so
    // a sketch can accompany `/design` (ADR-0019 decision 3). They stay
    // conversation-scoped in every case, including on `/start`: the create view
    // remains the only door to the project reference store.
    void send(draft.trim(), attachedFiles).then((started) => {
      // Clear ONLY on acceptance. A refused send leaves text and cards exactly
      // as they were, so retry is one click.
      if (started) {
        setDraft("");
        setAttachedFiles([]);
      }
    });
  };

  // Rotation is a PROJECT-WIDE act now (#430 D4): it demotes the thread for
  // every member, so it is confirmed — never gated. Gating on engagement would
  // deadlock the escape hatch (an abandoned interview blocks rotation forever);
  // instead the dialog NAMES what is at stake, so the click is informed where a
  // generic "are you sure?" would be muscle-memoried through.
  const [confirmNewOpen, setConfirmNewOpen] = useState(false);
  const confirmBody = teammateRunning
    ? `The agent is still working on ${teammateRunning}'s request. Starting a new conversation replaces the thread for everyone on the project; the running work continues but its narration will no longer be visible.`
    : isSending
      ? "The agent is still working on your request. Starting a new conversation replaces the thread for everyone on the project; the running work continues but its narration will no longer be visible."
      : answerableIds.size > 0
        ? `The agent is waiting on ${answerableIds.size === 1 ? "an unanswered question" : `${answerableIds.size} unanswered questions`}. Starting a new conversation abandons them for everyone on the project.`
        : "This starts a fresh conversation for everyone on the project.";
  const onConfirmNewConversation = () => {
    setConfirmNewOpen(false);
    newConversation();
    setDraft("");
    // A fresh thread starts clean: attachments are conversation-scoped, so
    // carrying them into a new one would contradict the only guarantee the
    // feature makes.
    setAttachedFiles([]);
  };

  return (
    <Box
      sx={{
        position: "relative",
        width,
        flexShrink: 0,
        height: "100%",
        display: "flex",
        flexDirection: "column",
        borderLeft: 1,
        borderColor: "divider",
        bgcolor: "background.paper",
      }}
    >
      {/* Drag handle on the left edge. */}
      <Box
        role="separator"
        aria-orientation="vertical"
        aria-label="Resize agent panel"
        aria-valuenow={width}
        aria-valuemin={MIN_WIDTH}
        aria-valuemax={MAX_WIDTH}
        tabIndex={0}
        onMouseDown={(e) => {
          dragRef.current = { startX: e.clientX, startW: width };
          setDragging(true);
          e.preventDefault();
        }}
        onKeyDown={(e) => {
          if (e.key === "ArrowLeft") setWidth((w) => clampWidth(w + WIDTH_STEP));
          else if (e.key === "ArrowRight") setWidth((w) => clampWidth(w - WIDTH_STEP));
        }}
        sx={{
          position: "absolute",
          left: 0,
          top: 0,
          bottom: 0,
          width: 6,
          ml: "-3px",
          cursor: "col-resize",
          zIndex: 1,
          "&:hover, &:focus-visible": { bgcolor: "primary.main", opacity: 0.4 },
          ...(dragging ? { bgcolor: "primary.main", opacity: 0.4 } : {}),
        }}
      />

      {/* Header */}
      <Stack
        direction="row"
        spacing={1}
        sx={{ alignItems: "center", px: 2, py: 1.25 }}
      >
        <Sparkles size={18} color="var(--oxygen-palette-primary-main, currentColor)" />
        <Typography variant="body2" sx={{ fontWeight: 600, flexGrow: 1 }}>
          Agent
        </Typography>
        {participants.length > 0 && (
          <AvatarGroup
            max={4}
            sx={{
              mr: 0.5,
              "& .MuiAvatar-root": { width: 24, height: 24, fontSize: "0.7rem" },
            }}
          >
            {participants.map((p) => (
              <Tooltip key={p.id} title={p.displayName}>
                <Avatar sx={{ bgcolor: p.isOwn ? "primary.main" : "info.main" }}>
                  {initialOf(p.displayName)}
                </Avatar>
              </Tooltip>
            ))}
          </AvatarGroup>
        )}
        <Tooltip title="New conversation">
          <span>
            <IconButton
              size="small"
              aria-label="New conversation"
              onClick={() => setConfirmNewOpen(true)}
            >
              <SquarePen size={16} />
            </IconButton>
          </span>
        </Tooltip>
        {specWorkspace ? (
          <Tooltip title="Open spec workspace">
            <IconButton size="small" aria-label="Open spec workspace" onClick={openSpec}>
              <ExternalLink size={16} />
            </IconButton>
          </Tooltip>
        ) : null}
        <IconButton size="small" aria-label="Close agent chat" onClick={onClose}>
          <XIcon size={16} />
        </IconButton>
      </Stack>
      <Divider />

      {/* Feed */}
      <Box ref={scrollRef} sx={{ flexGrow: 1, overflow: "auto", p: 2 }}>
        <Box ref={contentRef}>
          {feed.length === 0 ? (
            <Stack
              spacing={2}
              sx={{ alignItems: "center", textAlign: "center", mt: 5, px: 1 }}
            >
              <Avatar sx={{ width: 48, height: 48, bgcolor: "primary.main" }}>
                <Sparkles size={24} />
              </Avatar>
              <Typography variant="subtitle2">Hi! I&apos;m your Agent.</Typography>
              <Typography variant="body2" color="text.secondary">
                This is where we talk through what you&apos;re building. Ask
                about a decision, change what&apos;s in scope, or take up
                anything I marked as assumed.
              </Typography>
              <Stack
                direction="row"
                spacing={1}
                useFlexGap
                sx={{ flexWrap: "wrap", justifyContent: "center" }}
              >
                {SUGGESTIONS.map((s) => (
                  <Chip
                    key={s}
                    label={s}
                    variant="outlined"
                    size="small"
                    onClick={() => setDraft(s)}
                    sx={{ cursor: "pointer" }}
                  />
                ))}
              </Stack>
            </Stack>
          ) : (
            <MessageList
              feed={feed}
              expandedGroups={expandedGroups}
              onToggleGroup={toggleGroup}
              onOpenSpec={openSpec}
              showSpecLink={specWorkspace}
              showWorkingTail={showWorkingTail}
            />
          )}
        </Box>
      </Box>

      {/* Composer. The scoped launchers used to sit here behind an `Actions ▾`
          menu of raw slash commands (#372); each one changes a specific place
          in the PRD, so each is now offered AT that place as a code lens
          (#579) — where the subject comes from the line the user clicked
          rather than from their memory. */}
      <ChatInput
        value={draft}
        onChange={setDraft}
        onSubmit={submit}
        files={attachedFiles}
        onFilesChange={setAttachedFiles}
        disabled={inputDisabled}
        contextLabel={displayName ?? projectName}
        hint={hint}
      />
      <Dialog open={confirmNewOpen} onClose={() => setConfirmNewOpen(false)} maxWidth="xs" fullWidth>
        <DialogTitle>Start a new conversation?</DialogTitle>
        <DialogContent>
          <Typography variant="body2" color="text.secondary">
            {confirmBody}
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setConfirmNewOpen(false)}>Cancel</Button>
          <Button variant="contained" onClick={onConfirmNewConversation}>
            Start new conversation
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
