// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/aep/aep-api/internal/clients/openchoreo"
	"github.com/wso2/aep/aep-api/internal/gen"
)

// Ensure, that ComponentClientMock does implement openchoreo.ComponentClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.ComponentClient = &ComponentClientMock{}

// ComponentClientMock is a mock implementation of openchoreo.ComponentClient.
//
//	func TestSomethingThatUsesComponentClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.ComponentClient
//		mockedComponentClient := &ComponentClientMock{
//			ApplyComponentSpecFunc: func(ctx context.Context, orgName string, projectName string, componentName string, desired openchoreo.ComponentSpecDesired) error {
//				panic("mock out the ApplyComponentSpec method")
//			},
//			ApplyReleaseBindingFunc: func(ctx context.Context, orgName string, projectName string, in openchoreo.ReleaseBindingDesired) error {
//				panic("mock out the ApplyReleaseBinding method")
//			},
//			CreateComponentFunc: func(ctx context.Context, orgName string, projectName string, req *openchoreo.CreateComponentRequest) (*gen.Component, error) {
//				panic("mock out the CreateComponent method")
//			},
//			DeleteComponentFunc: func(ctx context.Context, orgName string, projectName string, componentName string) error {
//				panic("mock out the DeleteComponent method")
//			},
//			EnsureComponentTypeFunc: func(ctx context.Context, orgName string, body map[string]any) error {
//				panic("mock out the EnsureComponentType method")
//			},
//			EnsureReleaseFunc: func(ctx context.Context, orgName string, projectName string, componentName string, releaseName string) (string, error) {
//				panic("mock out the EnsureRelease method")
//			},
//			EnsureReleaseBindingFunc: func(ctx context.Context, orgName string, projectName string, componentName string, environment string, releaseName string) error {
//				panic("mock out the EnsureReleaseBinding method")
//			},
//			EnsureWorkloadFunc: func(ctx context.Context, orgName string, projectName string, in openchoreo.WorkloadInput) error {
//				panic("mock out the EnsureWorkload method")
//			},
//			GetComponentFunc: func(ctx context.Context, orgName string, projectName string, componentName string) (*gen.Component, error) {
//				panic("mock out the GetComponent method")
//			},
//			GetReleaseBindingStatusFunc: func(ctx context.Context, orgName string, projectName string, componentName string, environment string) (*openchoreo.ReleaseBindingSummary, error) {
//				panic("mock out the GetReleaseBindingStatus method")
//			},
//			GetWorkflowRunFunc: func(ctx context.Context, orgName string, runName string) (*gen.WorkflowRun, error) {
//				panic("mock out the GetWorkflowRun method")
//			},
//			ListBuildRunsFunc: func(ctx context.Context, orgName string, projectName string, componentName string) ([]openchoreo.BuildRunSummary, error) {
//				panic("mock out the ListBuildRuns method")
//			},
//			ListComponentsFunc: func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.ComponentList, error) {
//				panic("mock out the ListComponents method")
//			},
//			ListDeploymentsFunc: func(ctx context.Context, orgName string, projectName string, componentName string) (*gen.DeploymentList, error) {
//				panic("mock out the ListDeployments method")
//			},
//			ListInternalComponentsFunc: func(ctx context.Context, orgName string, projectName string) ([]openchoreo.InternalComponent, error) {
//				panic("mock out the ListInternalComponents method")
//			},
//			ListProjectReleaseBindingsFunc: func(ctx context.Context, orgName string, projectName string) ([]openchoreo.ReleaseBindingSummary, error) {
//				panic("mock out the ListProjectReleaseBindings method")
//			},
//			ListProjectWorkflowRunsFunc: func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.WorkflowRunList, error) {
//				panic("mock out the ListProjectWorkflowRuns method")
//			},
//			ListWorkflowRunsFunc: func(ctx context.Context, orgName string, projectName string, componentName string, limit int, cursor string) (*gen.WorkflowRunList, error) {
//				panic("mock out the ListWorkflowRuns method")
//			},
//			TriggerBuildFunc: func(ctx context.Context, orgName string, projectName string, componentName string, secretRef string, runName string) (*gen.WorkflowRun, error) {
//				panic("mock out the TriggerBuild method")
//			},
//			TriggerBuildAtCommitFunc: func(ctx context.Context, orgName string, projectName string, componentName string, commitSHA string, secretRef string, runName string) (*gen.WorkflowRun, error) {
//				panic("mock out the TriggerBuildAtCommit method")
//			},
//			UpdateComponentTraitEnvironmentConfigsFunc: func(ctx context.Context, orgName string, projectName string, componentName string, configs map[string]map[string]interface{}) error {
//				panic("mock out the UpdateComponentTraitEnvironmentConfigs method")
//			},
//		}
//
//		// use mockedComponentClient in code that requires openchoreo.ComponentClient
//		// and then make assertions.
//
//	}
type ComponentClientMock struct {
	// ApplyComponentSpecFunc mocks the ApplyComponentSpec method.
	ApplyComponentSpecFunc func(ctx context.Context, orgName string, projectName string, componentName string, desired openchoreo.ComponentSpecDesired) error

	// ApplyReleaseBindingFunc mocks the ApplyReleaseBinding method.
	ApplyReleaseBindingFunc func(ctx context.Context, orgName string, projectName string, in openchoreo.ReleaseBindingDesired) error

	// CreateComponentFunc mocks the CreateComponent method.
	CreateComponentFunc func(ctx context.Context, orgName string, projectName string, req *openchoreo.CreateComponentRequest) (*gen.Component, error)

	// DeleteComponentFunc mocks the DeleteComponent method.
	DeleteComponentFunc func(ctx context.Context, orgName string, projectName string, componentName string) error

	// EnsureComponentTypeFunc mocks the EnsureComponentType method.
	EnsureComponentTypeFunc func(ctx context.Context, orgName string, body map[string]any) error

	// EnsureReleaseFunc mocks the EnsureRelease method.
	EnsureReleaseFunc func(ctx context.Context, orgName string, projectName string, componentName string, releaseName string) (string, error)

	// EnsureReleaseBindingFunc mocks the EnsureReleaseBinding method.
	EnsureReleaseBindingFunc func(ctx context.Context, orgName string, projectName string, componentName string, environment string, releaseName string) error

	// EnsureWorkloadFunc mocks the EnsureWorkload method.
	EnsureWorkloadFunc func(ctx context.Context, orgName string, projectName string, in openchoreo.WorkloadInput) error

	// GetComponentFunc mocks the GetComponent method.
	GetComponentFunc func(ctx context.Context, orgName string, projectName string, componentName string) (*gen.Component, error)

	// GetReleaseBindingStatusFunc mocks the GetReleaseBindingStatus method.
	GetReleaseBindingStatusFunc func(ctx context.Context, orgName string, projectName string, componentName string, environment string) (*openchoreo.ReleaseBindingSummary, error)

	// GetWorkflowRunFunc mocks the GetWorkflowRun method.
	GetWorkflowRunFunc func(ctx context.Context, orgName string, runName string) (*gen.WorkflowRun, error)

	// ListBuildRunsFunc mocks the ListBuildRuns method.
	ListBuildRunsFunc func(ctx context.Context, orgName string, projectName string, componentName string) ([]openchoreo.BuildRunSummary, error)

	// ListComponentsFunc mocks the ListComponents method.
	ListComponentsFunc func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.ComponentList, error)

	// ListDeploymentsFunc mocks the ListDeployments method.
	ListDeploymentsFunc func(ctx context.Context, orgName string, projectName string, componentName string) (*gen.DeploymentList, error)

	// ListInternalComponentsFunc mocks the ListInternalComponents method.
	ListInternalComponentsFunc func(ctx context.Context, orgName string, projectName string) ([]openchoreo.InternalComponent, error)

	// ListProjectReleaseBindingsFunc mocks the ListProjectReleaseBindings method.
	ListProjectReleaseBindingsFunc func(ctx context.Context, orgName string, projectName string) ([]openchoreo.ReleaseBindingSummary, error)

	// ListProjectWorkflowRunsFunc mocks the ListProjectWorkflowRuns method.
	ListProjectWorkflowRunsFunc func(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.WorkflowRunList, error)

	// ListWorkflowRunsFunc mocks the ListWorkflowRuns method.
	ListWorkflowRunsFunc func(ctx context.Context, orgName string, projectName string, componentName string, limit int, cursor string) (*gen.WorkflowRunList, error)

	// TriggerBuildFunc mocks the TriggerBuild method.
	TriggerBuildFunc func(ctx context.Context, orgName string, projectName string, componentName string, secretRef string, runName string) (*gen.WorkflowRun, error)

	// TriggerBuildAtCommitFunc mocks the TriggerBuildAtCommit method.
	TriggerBuildAtCommitFunc func(ctx context.Context, orgName string, projectName string, componentName string, commitSHA string, secretRef string, runName string) (*gen.WorkflowRun, error)

	// UpdateComponentTraitEnvironmentConfigsFunc mocks the UpdateComponentTraitEnvironmentConfigs method.
	UpdateComponentTraitEnvironmentConfigsFunc func(ctx context.Context, orgName string, projectName string, componentName string, configs map[string]map[string]interface{}) error

	// calls tracks calls to the methods.
	calls struct {
		// ApplyComponentSpec holds details about calls to the ApplyComponentSpec method.
		ApplyComponentSpec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Desired is the desired argument value.
			Desired openchoreo.ComponentSpecDesired
		}
		// ApplyReleaseBinding holds details about calls to the ApplyReleaseBinding method.
		ApplyReleaseBinding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// In is the in argument value.
			In openchoreo.ReleaseBindingDesired
		}
		// CreateComponent holds details about calls to the CreateComponent method.
		CreateComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Req is the req argument value.
			Req *openchoreo.CreateComponentRequest
		}
		// DeleteComponent holds details about calls to the DeleteComponent method.
		DeleteComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// EnsureComponentType holds details about calls to the EnsureComponentType method.
		EnsureComponentType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// Body is the body argument value.
			Body map[string]any
		}
		// EnsureRelease holds details about calls to the EnsureRelease method.
		EnsureRelease []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// ReleaseName is the releaseName argument value.
			ReleaseName string
		}
		// EnsureReleaseBinding holds details about calls to the EnsureReleaseBinding method.
		EnsureReleaseBinding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Environment is the environment argument value.
			Environment string
			// ReleaseName is the releaseName argument value.
			ReleaseName string
		}
		// EnsureWorkload holds details about calls to the EnsureWorkload method.
		EnsureWorkload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// In is the in argument value.
			In openchoreo.WorkloadInput
		}
		// GetComponent holds details about calls to the GetComponent method.
		GetComponent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// GetReleaseBindingStatus holds details about calls to the GetReleaseBindingStatus method.
		GetReleaseBindingStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Environment is the environment argument value.
			Environment string
		}
		// GetWorkflowRun holds details about calls to the GetWorkflowRun method.
		GetWorkflowRun []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// RunName is the runName argument value.
			RunName string
		}
		// ListBuildRuns holds details about calls to the ListBuildRuns method.
		ListBuildRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// ListComponents holds details about calls to the ListComponents method.
		ListComponents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Limit is the limit argument value.
			Limit int
			// Cursor is the cursor argument value.
			Cursor string
		}
		// ListDeployments holds details about calls to the ListDeployments method.
		ListDeployments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
		}
		// ListInternalComponents holds details about calls to the ListInternalComponents method.
		ListInternalComponents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// ListProjectReleaseBindings holds details about calls to the ListProjectReleaseBindings method.
		ListProjectReleaseBindings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// ListProjectWorkflowRuns holds details about calls to the ListProjectWorkflowRuns method.
		ListProjectWorkflowRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Limit is the limit argument value.
			Limit int
			// Cursor is the cursor argument value.
			Cursor string
		}
		// ListWorkflowRuns holds details about calls to the ListWorkflowRuns method.
		ListWorkflowRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Limit is the limit argument value.
			Limit int
			// Cursor is the cursor argument value.
			Cursor string
		}
		// TriggerBuild holds details about calls to the TriggerBuild method.
		TriggerBuild []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// SecretRef is the secretRef argument value.
			SecretRef string
			// RunName is the runName argument value.
			RunName string
		}
		// TriggerBuildAtCommit holds details about calls to the TriggerBuildAtCommit method.
		TriggerBuildAtCommit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// CommitSHA is the commitSHA argument value.
			CommitSHA string
			// SecretRef is the secretRef argument value.
			SecretRef string
			// RunName is the runName argument value.
			RunName string
		}
		// UpdateComponentTraitEnvironmentConfigs holds details about calls to the UpdateComponentTraitEnvironmentConfigs method.
		UpdateComponentTraitEnvironmentConfigs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// ProjectName is the projectName argument value.
			ProjectName string
			// ComponentName is the componentName argument value.
			ComponentName string
			// Configs is the configs argument value.
			Configs map[string]map[string]interface{}
		}
	}
	lockApplyComponentSpec                     sync.RWMutex
	lockApplyReleaseBinding                    sync.RWMutex
	lockCreateComponent                        sync.RWMutex
	lockDeleteComponent                        sync.RWMutex
	lockEnsureComponentType                    sync.RWMutex
	lockEnsureRelease                          sync.RWMutex
	lockEnsureReleaseBinding                   sync.RWMutex
	lockEnsureWorkload                         sync.RWMutex
	lockGetComponent                           sync.RWMutex
	lockGetReleaseBindingStatus                sync.RWMutex
	lockGetWorkflowRun                         sync.RWMutex
	lockListBuildRuns                          sync.RWMutex
	lockListComponents                         sync.RWMutex
	lockListDeployments                        sync.RWMutex
	lockListInternalComponents                 sync.RWMutex
	lockListProjectReleaseBindings             sync.RWMutex
	lockListProjectWorkflowRuns                sync.RWMutex
	lockListWorkflowRuns                       sync.RWMutex
	lockTriggerBuild                           sync.RWMutex
	lockTriggerBuildAtCommit                   sync.RWMutex
	lockUpdateComponentTraitEnvironmentConfigs sync.RWMutex
}

// ApplyComponentSpec calls ApplyComponentSpecFunc.
func (mock *ComponentClientMock) ApplyComponentSpec(ctx context.Context, orgName string, projectName string, componentName string, desired openchoreo.ComponentSpecDesired) error {
	if mock.ApplyComponentSpecFunc == nil {
		panic("ComponentClientMock.ApplyComponentSpecFunc: method is nil but ComponentClient.ApplyComponentSpec was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Desired       openchoreo.ComponentSpecDesired
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Desired:       desired,
	}
	mock.lockApplyComponentSpec.Lock()
	mock.calls.ApplyComponentSpec = append(mock.calls.ApplyComponentSpec, callInfo)
	mock.lockApplyComponentSpec.Unlock()
	return mock.ApplyComponentSpecFunc(ctx, orgName, projectName, componentName, desired)
}

// ApplyComponentSpecCalls gets all the calls that were made to ApplyComponentSpec.
// Check the length with:
//
//	len(mockedComponentClient.ApplyComponentSpecCalls())
func (mock *ComponentClientMock) ApplyComponentSpecCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Desired       openchoreo.ComponentSpecDesired
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Desired       openchoreo.ComponentSpecDesired
	}
	mock.lockApplyComponentSpec.RLock()
	calls = mock.calls.ApplyComponentSpec
	mock.lockApplyComponentSpec.RUnlock()
	return calls
}

// ApplyReleaseBinding calls ApplyReleaseBindingFunc.
func (mock *ComponentClientMock) ApplyReleaseBinding(ctx context.Context, orgName string, projectName string, in openchoreo.ReleaseBindingDesired) error {
	if mock.ApplyReleaseBindingFunc == nil {
		panic("ComponentClientMock.ApplyReleaseBindingFunc: method is nil but ComponentClient.ApplyReleaseBinding was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		In          openchoreo.ReleaseBindingDesired
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		In:          in,
	}
	mock.lockApplyReleaseBinding.Lock()
	mock.calls.ApplyReleaseBinding = append(mock.calls.ApplyReleaseBinding, callInfo)
	mock.lockApplyReleaseBinding.Unlock()
	return mock.ApplyReleaseBindingFunc(ctx, orgName, projectName, in)
}

// ApplyReleaseBindingCalls gets all the calls that were made to ApplyReleaseBinding.
// Check the length with:
//
//	len(mockedComponentClient.ApplyReleaseBindingCalls())
func (mock *ComponentClientMock) ApplyReleaseBindingCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	In          openchoreo.ReleaseBindingDesired
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		In          openchoreo.ReleaseBindingDesired
	}
	mock.lockApplyReleaseBinding.RLock()
	calls = mock.calls.ApplyReleaseBinding
	mock.lockApplyReleaseBinding.RUnlock()
	return calls
}

// CreateComponent calls CreateComponentFunc.
func (mock *ComponentClientMock) CreateComponent(ctx context.Context, orgName string, projectName string, req *openchoreo.CreateComponentRequest) (*gen.Component, error) {
	if mock.CreateComponentFunc == nil {
		panic("ComponentClientMock.CreateComponentFunc: method is nil but ComponentClient.CreateComponent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Req         *openchoreo.CreateComponentRequest
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		Req:         req,
	}
	mock.lockCreateComponent.Lock()
	mock.calls.CreateComponent = append(mock.calls.CreateComponent, callInfo)
	mock.lockCreateComponent.Unlock()
	return mock.CreateComponentFunc(ctx, orgName, projectName, req)
}

// CreateComponentCalls gets all the calls that were made to CreateComponent.
// Check the length with:
//
//	len(mockedComponentClient.CreateComponentCalls())
func (mock *ComponentClientMock) CreateComponentCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	Req         *openchoreo.CreateComponentRequest
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Req         *openchoreo.CreateComponentRequest
	}
	mock.lockCreateComponent.RLock()
	calls = mock.calls.CreateComponent
	mock.lockCreateComponent.RUnlock()
	return calls
}

// DeleteComponent calls DeleteComponentFunc.
func (mock *ComponentClientMock) DeleteComponent(ctx context.Context, orgName string, projectName string, componentName string) error {
	if mock.DeleteComponentFunc == nil {
		panic("ComponentClientMock.DeleteComponentFunc: method is nil but ComponentClient.DeleteComponent was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockDeleteComponent.Lock()
	mock.calls.DeleteComponent = append(mock.calls.DeleteComponent, callInfo)
	mock.lockDeleteComponent.Unlock()
	return mock.DeleteComponentFunc(ctx, orgName, projectName, componentName)
}

// DeleteComponentCalls gets all the calls that were made to DeleteComponent.
// Check the length with:
//
//	len(mockedComponentClient.DeleteComponentCalls())
func (mock *ComponentClientMock) DeleteComponentCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockDeleteComponent.RLock()
	calls = mock.calls.DeleteComponent
	mock.lockDeleteComponent.RUnlock()
	return calls
}

// EnsureComponentType calls EnsureComponentTypeFunc.
func (mock *ComponentClientMock) EnsureComponentType(ctx context.Context, orgName string, body map[string]any) error {
	if mock.EnsureComponentTypeFunc == nil {
		panic("ComponentClientMock.EnsureComponentTypeFunc: method is nil but ComponentClient.EnsureComponentType was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		Body    map[string]any
	}{
		Ctx:     ctx,
		OrgName: orgName,
		Body:    body,
	}
	mock.lockEnsureComponentType.Lock()
	mock.calls.EnsureComponentType = append(mock.calls.EnsureComponentType, callInfo)
	mock.lockEnsureComponentType.Unlock()
	return mock.EnsureComponentTypeFunc(ctx, orgName, body)
}

// EnsureComponentTypeCalls gets all the calls that were made to EnsureComponentType.
// Check the length with:
//
//	len(mockedComponentClient.EnsureComponentTypeCalls())
func (mock *ComponentClientMock) EnsureComponentTypeCalls() []struct {
	Ctx     context.Context
	OrgName string
	Body    map[string]any
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		Body    map[string]any
	}
	mock.lockEnsureComponentType.RLock()
	calls = mock.calls.EnsureComponentType
	mock.lockEnsureComponentType.RUnlock()
	return calls
}

// EnsureRelease calls EnsureReleaseFunc.
func (mock *ComponentClientMock) EnsureRelease(ctx context.Context, orgName string, projectName string, componentName string, releaseName string) (string, error) {
	if mock.EnsureReleaseFunc == nil {
		panic("ComponentClientMock.EnsureReleaseFunc: method is nil but ComponentClient.EnsureRelease was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		ReleaseName   string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		ReleaseName:   releaseName,
	}
	mock.lockEnsureRelease.Lock()
	mock.calls.EnsureRelease = append(mock.calls.EnsureRelease, callInfo)
	mock.lockEnsureRelease.Unlock()
	return mock.EnsureReleaseFunc(ctx, orgName, projectName, componentName, releaseName)
}

// EnsureReleaseCalls gets all the calls that were made to EnsureRelease.
// Check the length with:
//
//	len(mockedComponentClient.EnsureReleaseCalls())
func (mock *ComponentClientMock) EnsureReleaseCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	ReleaseName   string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		ReleaseName   string
	}
	mock.lockEnsureRelease.RLock()
	calls = mock.calls.EnsureRelease
	mock.lockEnsureRelease.RUnlock()
	return calls
}

// EnsureReleaseBinding calls EnsureReleaseBindingFunc.
func (mock *ComponentClientMock) EnsureReleaseBinding(ctx context.Context, orgName string, projectName string, componentName string, environment string, releaseName string) error {
	if mock.EnsureReleaseBindingFunc == nil {
		panic("ComponentClientMock.EnsureReleaseBindingFunc: method is nil but ComponentClient.EnsureReleaseBinding was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Environment   string
		ReleaseName   string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Environment:   environment,
		ReleaseName:   releaseName,
	}
	mock.lockEnsureReleaseBinding.Lock()
	mock.calls.EnsureReleaseBinding = append(mock.calls.EnsureReleaseBinding, callInfo)
	mock.lockEnsureReleaseBinding.Unlock()
	return mock.EnsureReleaseBindingFunc(ctx, orgName, projectName, componentName, environment, releaseName)
}

// EnsureReleaseBindingCalls gets all the calls that were made to EnsureReleaseBinding.
// Check the length with:
//
//	len(mockedComponentClient.EnsureReleaseBindingCalls())
func (mock *ComponentClientMock) EnsureReleaseBindingCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Environment   string
	ReleaseName   string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Environment   string
		ReleaseName   string
	}
	mock.lockEnsureReleaseBinding.RLock()
	calls = mock.calls.EnsureReleaseBinding
	mock.lockEnsureReleaseBinding.RUnlock()
	return calls
}

// EnsureWorkload calls EnsureWorkloadFunc.
func (mock *ComponentClientMock) EnsureWorkload(ctx context.Context, orgName string, projectName string, in openchoreo.WorkloadInput) error {
	if mock.EnsureWorkloadFunc == nil {
		panic("ComponentClientMock.EnsureWorkloadFunc: method is nil but ComponentClient.EnsureWorkload was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		In          openchoreo.WorkloadInput
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		In:          in,
	}
	mock.lockEnsureWorkload.Lock()
	mock.calls.EnsureWorkload = append(mock.calls.EnsureWorkload, callInfo)
	mock.lockEnsureWorkload.Unlock()
	return mock.EnsureWorkloadFunc(ctx, orgName, projectName, in)
}

// EnsureWorkloadCalls gets all the calls that were made to EnsureWorkload.
// Check the length with:
//
//	len(mockedComponentClient.EnsureWorkloadCalls())
func (mock *ComponentClientMock) EnsureWorkloadCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	In          openchoreo.WorkloadInput
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		In          openchoreo.WorkloadInput
	}
	mock.lockEnsureWorkload.RLock()
	calls = mock.calls.EnsureWorkload
	mock.lockEnsureWorkload.RUnlock()
	return calls
}

// GetComponent calls GetComponentFunc.
func (mock *ComponentClientMock) GetComponent(ctx context.Context, orgName string, projectName string, componentName string) (*gen.Component, error) {
	if mock.GetComponentFunc == nil {
		panic("ComponentClientMock.GetComponentFunc: method is nil but ComponentClient.GetComponent was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockGetComponent.Lock()
	mock.calls.GetComponent = append(mock.calls.GetComponent, callInfo)
	mock.lockGetComponent.Unlock()
	return mock.GetComponentFunc(ctx, orgName, projectName, componentName)
}

// GetComponentCalls gets all the calls that were made to GetComponent.
// Check the length with:
//
//	len(mockedComponentClient.GetComponentCalls())
func (mock *ComponentClientMock) GetComponentCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockGetComponent.RLock()
	calls = mock.calls.GetComponent
	mock.lockGetComponent.RUnlock()
	return calls
}

// GetReleaseBindingStatus calls GetReleaseBindingStatusFunc.
func (mock *ComponentClientMock) GetReleaseBindingStatus(ctx context.Context, orgName string, projectName string, componentName string, environment string) (*openchoreo.ReleaseBindingSummary, error) {
	if mock.GetReleaseBindingStatusFunc == nil {
		panic("ComponentClientMock.GetReleaseBindingStatusFunc: method is nil but ComponentClient.GetReleaseBindingStatus was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Environment   string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Environment:   environment,
	}
	mock.lockGetReleaseBindingStatus.Lock()
	mock.calls.GetReleaseBindingStatus = append(mock.calls.GetReleaseBindingStatus, callInfo)
	mock.lockGetReleaseBindingStatus.Unlock()
	return mock.GetReleaseBindingStatusFunc(ctx, orgName, projectName, componentName, environment)
}

// GetReleaseBindingStatusCalls gets all the calls that were made to GetReleaseBindingStatus.
// Check the length with:
//
//	len(mockedComponentClient.GetReleaseBindingStatusCalls())
func (mock *ComponentClientMock) GetReleaseBindingStatusCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Environment   string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Environment   string
	}
	mock.lockGetReleaseBindingStatus.RLock()
	calls = mock.calls.GetReleaseBindingStatus
	mock.lockGetReleaseBindingStatus.RUnlock()
	return calls
}

// GetWorkflowRun calls GetWorkflowRunFunc.
func (mock *ComponentClientMock) GetWorkflowRun(ctx context.Context, orgName string, runName string) (*gen.WorkflowRun, error) {
	if mock.GetWorkflowRunFunc == nil {
		panic("ComponentClientMock.GetWorkflowRunFunc: method is nil but ComponentClient.GetWorkflowRun was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		RunName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
		RunName: runName,
	}
	mock.lockGetWorkflowRun.Lock()
	mock.calls.GetWorkflowRun = append(mock.calls.GetWorkflowRun, callInfo)
	mock.lockGetWorkflowRun.Unlock()
	return mock.GetWorkflowRunFunc(ctx, orgName, runName)
}

// GetWorkflowRunCalls gets all the calls that were made to GetWorkflowRun.
// Check the length with:
//
//	len(mockedComponentClient.GetWorkflowRunCalls())
func (mock *ComponentClientMock) GetWorkflowRunCalls() []struct {
	Ctx     context.Context
	OrgName string
	RunName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		RunName string
	}
	mock.lockGetWorkflowRun.RLock()
	calls = mock.calls.GetWorkflowRun
	mock.lockGetWorkflowRun.RUnlock()
	return calls
}

// ListBuildRuns calls ListBuildRunsFunc.
func (mock *ComponentClientMock) ListBuildRuns(ctx context.Context, orgName string, projectName string, componentName string) ([]openchoreo.BuildRunSummary, error) {
	if mock.ListBuildRunsFunc == nil {
		panic("ComponentClientMock.ListBuildRunsFunc: method is nil but ComponentClient.ListBuildRuns was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockListBuildRuns.Lock()
	mock.calls.ListBuildRuns = append(mock.calls.ListBuildRuns, callInfo)
	mock.lockListBuildRuns.Unlock()
	return mock.ListBuildRunsFunc(ctx, orgName, projectName, componentName)
}

// ListBuildRunsCalls gets all the calls that were made to ListBuildRuns.
// Check the length with:
//
//	len(mockedComponentClient.ListBuildRunsCalls())
func (mock *ComponentClientMock) ListBuildRunsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockListBuildRuns.RLock()
	calls = mock.calls.ListBuildRuns
	mock.lockListBuildRuns.RUnlock()
	return calls
}

// ListComponents calls ListComponentsFunc.
func (mock *ComponentClientMock) ListComponents(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.ComponentList, error) {
	if mock.ListComponentsFunc == nil {
		panic("ComponentClientMock.ListComponentsFunc: method is nil but ComponentClient.ListComponents was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		Limit:       limit,
		Cursor:      cursor,
	}
	mock.lockListComponents.Lock()
	mock.calls.ListComponents = append(mock.calls.ListComponents, callInfo)
	mock.lockListComponents.Unlock()
	return mock.ListComponentsFunc(ctx, orgName, projectName, limit, cursor)
}

// ListComponentsCalls gets all the calls that were made to ListComponents.
// Check the length with:
//
//	len(mockedComponentClient.ListComponentsCalls())
func (mock *ComponentClientMock) ListComponentsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	Limit       int
	Cursor      string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}
	mock.lockListComponents.RLock()
	calls = mock.calls.ListComponents
	mock.lockListComponents.RUnlock()
	return calls
}

// ListDeployments calls ListDeploymentsFunc.
func (mock *ComponentClientMock) ListDeployments(ctx context.Context, orgName string, projectName string, componentName string) (*gen.DeploymentList, error) {
	if mock.ListDeploymentsFunc == nil {
		panic("ComponentClientMock.ListDeploymentsFunc: method is nil but ComponentClient.ListDeployments was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
	}
	mock.lockListDeployments.Lock()
	mock.calls.ListDeployments = append(mock.calls.ListDeployments, callInfo)
	mock.lockListDeployments.Unlock()
	return mock.ListDeploymentsFunc(ctx, orgName, projectName, componentName)
}

// ListDeploymentsCalls gets all the calls that were made to ListDeployments.
// Check the length with:
//
//	len(mockedComponentClient.ListDeploymentsCalls())
func (mock *ComponentClientMock) ListDeploymentsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
	}
	mock.lockListDeployments.RLock()
	calls = mock.calls.ListDeployments
	mock.lockListDeployments.RUnlock()
	return calls
}

// ListInternalComponents calls ListInternalComponentsFunc.
func (mock *ComponentClientMock) ListInternalComponents(ctx context.Context, orgName string, projectName string) ([]openchoreo.InternalComponent, error) {
	if mock.ListInternalComponentsFunc == nil {
		panic("ComponentClientMock.ListInternalComponentsFunc: method is nil but ComponentClient.ListInternalComponents was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
	}
	mock.lockListInternalComponents.Lock()
	mock.calls.ListInternalComponents = append(mock.calls.ListInternalComponents, callInfo)
	mock.lockListInternalComponents.Unlock()
	return mock.ListInternalComponentsFunc(ctx, orgName, projectName)
}

// ListInternalComponentsCalls gets all the calls that were made to ListInternalComponents.
// Check the length with:
//
//	len(mockedComponentClient.ListInternalComponentsCalls())
func (mock *ComponentClientMock) ListInternalComponentsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}
	mock.lockListInternalComponents.RLock()
	calls = mock.calls.ListInternalComponents
	mock.lockListInternalComponents.RUnlock()
	return calls
}

// ListProjectReleaseBindings calls ListProjectReleaseBindingsFunc.
func (mock *ComponentClientMock) ListProjectReleaseBindings(ctx context.Context, orgName string, projectName string) ([]openchoreo.ReleaseBindingSummary, error) {
	if mock.ListProjectReleaseBindingsFunc == nil {
		panic("ComponentClientMock.ListProjectReleaseBindingsFunc: method is nil but ComponentClient.ListProjectReleaseBindings was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
	}
	mock.lockListProjectReleaseBindings.Lock()
	mock.calls.ListProjectReleaseBindings = append(mock.calls.ListProjectReleaseBindings, callInfo)
	mock.lockListProjectReleaseBindings.Unlock()
	return mock.ListProjectReleaseBindingsFunc(ctx, orgName, projectName)
}

// ListProjectReleaseBindingsCalls gets all the calls that were made to ListProjectReleaseBindings.
// Check the length with:
//
//	len(mockedComponentClient.ListProjectReleaseBindingsCalls())
func (mock *ComponentClientMock) ListProjectReleaseBindingsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
	}
	mock.lockListProjectReleaseBindings.RLock()
	calls = mock.calls.ListProjectReleaseBindings
	mock.lockListProjectReleaseBindings.RUnlock()
	return calls
}

// ListProjectWorkflowRuns calls ListProjectWorkflowRunsFunc.
func (mock *ComponentClientMock) ListProjectWorkflowRuns(ctx context.Context, orgName string, projectName string, limit int, cursor string) (*gen.WorkflowRunList, error) {
	if mock.ListProjectWorkflowRunsFunc == nil {
		panic("ComponentClientMock.ListProjectWorkflowRunsFunc: method is nil but ComponentClient.ListProjectWorkflowRuns was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}{
		Ctx:         ctx,
		OrgName:     orgName,
		ProjectName: projectName,
		Limit:       limit,
		Cursor:      cursor,
	}
	mock.lockListProjectWorkflowRuns.Lock()
	mock.calls.ListProjectWorkflowRuns = append(mock.calls.ListProjectWorkflowRuns, callInfo)
	mock.lockListProjectWorkflowRuns.Unlock()
	return mock.ListProjectWorkflowRunsFunc(ctx, orgName, projectName, limit, cursor)
}

// ListProjectWorkflowRunsCalls gets all the calls that were made to ListProjectWorkflowRuns.
// Check the length with:
//
//	len(mockedComponentClient.ListProjectWorkflowRunsCalls())
func (mock *ComponentClientMock) ListProjectWorkflowRunsCalls() []struct {
	Ctx         context.Context
	OrgName     string
	ProjectName string
	Limit       int
	Cursor      string
} {
	var calls []struct {
		Ctx         context.Context
		OrgName     string
		ProjectName string
		Limit       int
		Cursor      string
	}
	mock.lockListProjectWorkflowRuns.RLock()
	calls = mock.calls.ListProjectWorkflowRuns
	mock.lockListProjectWorkflowRuns.RUnlock()
	return calls
}

// ListWorkflowRuns calls ListWorkflowRunsFunc.
func (mock *ComponentClientMock) ListWorkflowRuns(ctx context.Context, orgName string, projectName string, componentName string, limit int, cursor string) (*gen.WorkflowRunList, error) {
	if mock.ListWorkflowRunsFunc == nil {
		panic("ComponentClientMock.ListWorkflowRunsFunc: method is nil but ComponentClient.ListWorkflowRuns was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Limit         int
		Cursor        string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Limit:         limit,
		Cursor:        cursor,
	}
	mock.lockListWorkflowRuns.Lock()
	mock.calls.ListWorkflowRuns = append(mock.calls.ListWorkflowRuns, callInfo)
	mock.lockListWorkflowRuns.Unlock()
	return mock.ListWorkflowRunsFunc(ctx, orgName, projectName, componentName, limit, cursor)
}

// ListWorkflowRunsCalls gets all the calls that were made to ListWorkflowRuns.
// Check the length with:
//
//	len(mockedComponentClient.ListWorkflowRunsCalls())
func (mock *ComponentClientMock) ListWorkflowRunsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Limit         int
	Cursor        string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Limit         int
		Cursor        string
	}
	mock.lockListWorkflowRuns.RLock()
	calls = mock.calls.ListWorkflowRuns
	mock.lockListWorkflowRuns.RUnlock()
	return calls
}

// TriggerBuild calls TriggerBuildFunc.
func (mock *ComponentClientMock) TriggerBuild(ctx context.Context, orgName string, projectName string, componentName string, secretRef string, runName string) (*gen.WorkflowRun, error) {
	if mock.TriggerBuildFunc == nil {
		panic("ComponentClientMock.TriggerBuildFunc: method is nil but ComponentClient.TriggerBuild was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		SecretRef     string
		RunName       string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		SecretRef:     secretRef,
		RunName:       runName,
	}
	mock.lockTriggerBuild.Lock()
	mock.calls.TriggerBuild = append(mock.calls.TriggerBuild, callInfo)
	mock.lockTriggerBuild.Unlock()
	return mock.TriggerBuildFunc(ctx, orgName, projectName, componentName, secretRef, runName)
}

// TriggerBuildCalls gets all the calls that were made to TriggerBuild.
// Check the length with:
//
//	len(mockedComponentClient.TriggerBuildCalls())
func (mock *ComponentClientMock) TriggerBuildCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	SecretRef     string
	RunName       string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		SecretRef     string
		RunName       string
	}
	mock.lockTriggerBuild.RLock()
	calls = mock.calls.TriggerBuild
	mock.lockTriggerBuild.RUnlock()
	return calls
}

// TriggerBuildAtCommit calls TriggerBuildAtCommitFunc.
func (mock *ComponentClientMock) TriggerBuildAtCommit(ctx context.Context, orgName string, projectName string, componentName string, commitSHA string, secretRef string, runName string) (*gen.WorkflowRun, error) {
	if mock.TriggerBuildAtCommitFunc == nil {
		panic("ComponentClientMock.TriggerBuildAtCommitFunc: method is nil but ComponentClient.TriggerBuildAtCommit was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		CommitSHA     string
		SecretRef     string
		RunName       string
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		CommitSHA:     commitSHA,
		SecretRef:     secretRef,
		RunName:       runName,
	}
	mock.lockTriggerBuildAtCommit.Lock()
	mock.calls.TriggerBuildAtCommit = append(mock.calls.TriggerBuildAtCommit, callInfo)
	mock.lockTriggerBuildAtCommit.Unlock()
	return mock.TriggerBuildAtCommitFunc(ctx, orgName, projectName, componentName, commitSHA, secretRef, runName)
}

// TriggerBuildAtCommitCalls gets all the calls that were made to TriggerBuildAtCommit.
// Check the length with:
//
//	len(mockedComponentClient.TriggerBuildAtCommitCalls())
func (mock *ComponentClientMock) TriggerBuildAtCommitCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	CommitSHA     string
	SecretRef     string
	RunName       string
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		CommitSHA     string
		SecretRef     string
		RunName       string
	}
	mock.lockTriggerBuildAtCommit.RLock()
	calls = mock.calls.TriggerBuildAtCommit
	mock.lockTriggerBuildAtCommit.RUnlock()
	return calls
}

// UpdateComponentTraitEnvironmentConfigs calls UpdateComponentTraitEnvironmentConfigsFunc.
func (mock *ComponentClientMock) UpdateComponentTraitEnvironmentConfigs(ctx context.Context, orgName string, projectName string, componentName string, configs map[string]map[string]interface{}) error {
	if mock.UpdateComponentTraitEnvironmentConfigsFunc == nil {
		panic("ComponentClientMock.UpdateComponentTraitEnvironmentConfigsFunc: method is nil but ComponentClient.UpdateComponentTraitEnvironmentConfigs was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Configs       map[string]map[string]interface{}
	}{
		Ctx:           ctx,
		OrgName:       orgName,
		ProjectName:   projectName,
		ComponentName: componentName,
		Configs:       configs,
	}
	mock.lockUpdateComponentTraitEnvironmentConfigs.Lock()
	mock.calls.UpdateComponentTraitEnvironmentConfigs = append(mock.calls.UpdateComponentTraitEnvironmentConfigs, callInfo)
	mock.lockUpdateComponentTraitEnvironmentConfigs.Unlock()
	return mock.UpdateComponentTraitEnvironmentConfigsFunc(ctx, orgName, projectName, componentName, configs)
}

// UpdateComponentTraitEnvironmentConfigsCalls gets all the calls that were made to UpdateComponentTraitEnvironmentConfigs.
// Check the length with:
//
//	len(mockedComponentClient.UpdateComponentTraitEnvironmentConfigsCalls())
func (mock *ComponentClientMock) UpdateComponentTraitEnvironmentConfigsCalls() []struct {
	Ctx           context.Context
	OrgName       string
	ProjectName   string
	ComponentName string
	Configs       map[string]map[string]interface{}
} {
	var calls []struct {
		Ctx           context.Context
		OrgName       string
		ProjectName   string
		ComponentName string
		Configs       map[string]map[string]interface{}
	}
	mock.lockUpdateComponentTraitEnvironmentConfigs.RLock()
	calls = mock.calls.UpdateComponentTraitEnvironmentConfigs
	mock.lockUpdateComponentTraitEnvironmentConfigs.RUnlock()
	return calls
}
