// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/aep/aep-api/internal/clients/openchoreo"
)

// Ensure, that ProjectCellClientMock does implement openchoreo.ProjectCellClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.ProjectCellClient = &ProjectCellClientMock{}

// ProjectCellClientMock is a mock implementation of openchoreo.ProjectCellClient.
//
//	func TestSomethingThatUsesProjectCellClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.ProjectCellClient
//		mockedProjectCellClient := &ProjectCellClientMock{
//			EnsureProjectReleaseBindingFunc: func(ctx context.Context, namespace string, projectName string, environment string) error {
//				panic("mock out the EnsureProjectReleaseBinding method")
//			},
//			PipelineEnvironmentsFunc: func(ctx context.Context, namespace string, pipelineName string) ([]string, error) {
//				panic("mock out the PipelineEnvironments method")
//			},
//		}
//
//		// use mockedProjectCellClient in code that requires openchoreo.ProjectCellClient
//		// and then make assertions.
//
//	}
type ProjectCellClientMock struct {
	// EnsureProjectReleaseBindingFunc mocks the EnsureProjectReleaseBinding method.
	EnsureProjectReleaseBindingFunc func(ctx context.Context, namespace string, projectName string, environment string) error

	// PipelineEnvironmentsFunc mocks the PipelineEnvironments method.
	PipelineEnvironmentsFunc func(ctx context.Context, namespace string, pipelineName string) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// EnsureProjectReleaseBinding holds details about calls to the EnsureProjectReleaseBinding method.
		EnsureProjectReleaseBinding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// ProjectName is the projectName argument value.
			ProjectName string
			// Environment is the environment argument value.
			Environment string
		}
		// PipelineEnvironments holds details about calls to the PipelineEnvironments method.
		PipelineEnvironments []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// PipelineName is the pipelineName argument value.
			PipelineName string
		}
	}
	lockEnsureProjectReleaseBinding sync.RWMutex
	lockPipelineEnvironments        sync.RWMutex
}

// EnsureProjectReleaseBinding calls EnsureProjectReleaseBindingFunc.
func (mock *ProjectCellClientMock) EnsureProjectReleaseBinding(ctx context.Context, namespace string, projectName string, environment string) error {
	if mock.EnsureProjectReleaseBindingFunc == nil {
		panic("ProjectCellClientMock.EnsureProjectReleaseBindingFunc: method is nil but ProjectCellClient.EnsureProjectReleaseBinding was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Namespace   string
		ProjectName string
		Environment string
	}{
		Ctx:         ctx,
		Namespace:   namespace,
		ProjectName: projectName,
		Environment: environment,
	}
	mock.lockEnsureProjectReleaseBinding.Lock()
	mock.calls.EnsureProjectReleaseBinding = append(mock.calls.EnsureProjectReleaseBinding, callInfo)
	mock.lockEnsureProjectReleaseBinding.Unlock()
	return mock.EnsureProjectReleaseBindingFunc(ctx, namespace, projectName, environment)
}

// EnsureProjectReleaseBindingCalls gets all the calls that were made to EnsureProjectReleaseBinding.
// Check the length with:
//
//	len(mockedProjectCellClient.EnsureProjectReleaseBindingCalls())
func (mock *ProjectCellClientMock) EnsureProjectReleaseBindingCalls() []struct {
	Ctx         context.Context
	Namespace   string
	ProjectName string
	Environment string
} {
	var calls []struct {
		Ctx         context.Context
		Namespace   string
		ProjectName string
		Environment string
	}
	mock.lockEnsureProjectReleaseBinding.RLock()
	calls = mock.calls.EnsureProjectReleaseBinding
	mock.lockEnsureProjectReleaseBinding.RUnlock()
	return calls
}

// PipelineEnvironments calls PipelineEnvironmentsFunc.
func (mock *ProjectCellClientMock) PipelineEnvironments(ctx context.Context, namespace string, pipelineName string) ([]string, error) {
	if mock.PipelineEnvironmentsFunc == nil {
		panic("ProjectCellClientMock.PipelineEnvironmentsFunc: method is nil but ProjectCellClient.PipelineEnvironments was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Namespace    string
		PipelineName string
	}{
		Ctx:          ctx,
		Namespace:    namespace,
		PipelineName: pipelineName,
	}
	mock.lockPipelineEnvironments.Lock()
	mock.calls.PipelineEnvironments = append(mock.calls.PipelineEnvironments, callInfo)
	mock.lockPipelineEnvironments.Unlock()
	return mock.PipelineEnvironmentsFunc(ctx, namespace, pipelineName)
}

// PipelineEnvironmentsCalls gets all the calls that were made to PipelineEnvironments.
// Check the length with:
//
//	len(mockedProjectCellClient.PipelineEnvironmentsCalls())
func (mock *ProjectCellClientMock) PipelineEnvironmentsCalls() []struct {
	Ctx          context.Context
	Namespace    string
	PipelineName string
} {
	var calls []struct {
		Ctx          context.Context
		Namespace    string
		PipelineName string
	}
	mock.lockPipelineEnvironments.RLock()
	calls = mock.calls.PipelineEnvironments
	mock.lockPipelineEnvironments.RUnlock()
	return calls
}
