// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/wso2/aep/aep-api/internal/clients/openchoreo"
)

// Ensure, that ResourceClientMock does implement openchoreo.ResourceClient.
// If this is not the case, regenerate this file with moq.
var _ openchoreo.ResourceClient = &ResourceClientMock{}

// ResourceClientMock is a mock implementation of openchoreo.ResourceClient.
//
//	func TestSomethingThatUsesResourceClient(t *testing.T) {
//
//		// make and configure a mocked openchoreo.ResourceClient
//		mockedResourceClient := &ResourceClientMock{
//			ApplyResourceFunc: func(ctx context.Context, namespace string, r *openchoreo.Resource) (*openchoreo.Resource, error) {
//				panic("mock out the ApplyResource method")
//			},
//			DeleteBindingFunc: func(ctx context.Context, namespace string, name string) error {
//				panic("mock out the DeleteBinding method")
//			},
//			DeleteResourceFunc: func(ctx context.Context, namespace string, name string) error {
//				panic("mock out the DeleteResource method")
//			},
//			DeleteResourceTypeFunc: func(ctx context.Context, namespace string, name string) error {
//				panic("mock out the DeleteResourceType method")
//			},
//			EnsureBindingFunc: func(ctx context.Context, namespace string, b *openchoreo.ResourceReleaseBinding) (*openchoreo.ResourceReleaseBinding, error) {
//				panic("mock out the EnsureBinding method")
//			},
//			EnsureResourceTypeFunc: func(ctx context.Context, namespace string, rt *openchoreo.ResourceType) (*openchoreo.ResourceType, error) {
//				panic("mock out the EnsureResourceType method")
//			},
//			GetBindingFunc: func(ctx context.Context, namespace string, name string) (*openchoreo.ResourceReleaseBinding, error) {
//				panic("mock out the GetBinding method")
//			},
//			GetResourceFunc: func(ctx context.Context, namespace string, name string) (*openchoreo.Resource, error) {
//				panic("mock out the GetResource method")
//			},
//			GetResourceTypeFunc: func(ctx context.Context, namespace string, name string) (*openchoreo.ResourceType, error) {
//				panic("mock out the GetResourceType method")
//			},
//			ListClusterResourceTypesFunc: func(ctx context.Context) ([]openchoreo.ResourceType, error) {
//				panic("mock out the ListClusterResourceTypes method")
//			},
//			ListResourceTypesFunc: func(ctx context.Context, namespace string) ([]openchoreo.ResourceType, error) {
//				panic("mock out the ListResourceTypes method")
//			},
//			ListWorkloadConsumerDepsFunc: func(ctx context.Context, orgHandle string, projectName string) ([]openchoreo.WorkloadConsumerDep, error) {
//				panic("mock out the ListWorkloadConsumerDeps method")
//			},
//			ListWorkloadEndpointsFunc: func(ctx context.Context, orgHandle string) ([]openchoreo.WorkloadEndpointInfo, error) {
//				panic("mock out the ListWorkloadEndpoints method")
//			},
//			PatchBindingEnvironmentConfigsFunc: func(ctx context.Context, orgID string, bindingName string, configs map[string]string) error {
//				panic("mock out the PatchBindingEnvironmentConfigs method")
//			},
//			UpdateResourceTypeFunc: func(ctx context.Context, namespace string, rt *openchoreo.ResourceType) (*openchoreo.ResourceType, error) {
//				panic("mock out the UpdateResourceType method")
//			},
//		}
//
//		// use mockedResourceClient in code that requires openchoreo.ResourceClient
//		// and then make assertions.
//
//	}
type ResourceClientMock struct {
	// ApplyResourceFunc mocks the ApplyResource method.
	ApplyResourceFunc func(ctx context.Context, namespace string, r *openchoreo.Resource) (*openchoreo.Resource, error)

	// DeleteBindingFunc mocks the DeleteBinding method.
	DeleteBindingFunc func(ctx context.Context, namespace string, name string) error

	// DeleteResourceFunc mocks the DeleteResource method.
	DeleteResourceFunc func(ctx context.Context, namespace string, name string) error

	// DeleteResourceTypeFunc mocks the DeleteResourceType method.
	DeleteResourceTypeFunc func(ctx context.Context, namespace string, name string) error

	// EnsureBindingFunc mocks the EnsureBinding method.
	EnsureBindingFunc func(ctx context.Context, namespace string, b *openchoreo.ResourceReleaseBinding) (*openchoreo.ResourceReleaseBinding, error)

	// EnsureResourceTypeFunc mocks the EnsureResourceType method.
	EnsureResourceTypeFunc func(ctx context.Context, namespace string, rt *openchoreo.ResourceType) (*openchoreo.ResourceType, error)

	// GetBindingFunc mocks the GetBinding method.
	GetBindingFunc func(ctx context.Context, namespace string, name string) (*openchoreo.ResourceReleaseBinding, error)

	// GetResourceFunc mocks the GetResource method.
	GetResourceFunc func(ctx context.Context, namespace string, name string) (*openchoreo.Resource, error)

	// GetResourceTypeFunc mocks the GetResourceType method.
	GetResourceTypeFunc func(ctx context.Context, namespace string, name string) (*openchoreo.ResourceType, error)

	// ListClusterResourceTypesFunc mocks the ListClusterResourceTypes method.
	ListClusterResourceTypesFunc func(ctx context.Context) ([]openchoreo.ResourceType, error)

	// ListResourceTypesFunc mocks the ListResourceTypes method.
	ListResourceTypesFunc func(ctx context.Context, namespace string) ([]openchoreo.ResourceType, error)

	// ListWorkloadConsumerDepsFunc mocks the ListWorkloadConsumerDeps method.
	ListWorkloadConsumerDepsFunc func(ctx context.Context, orgHandle string, projectName string) ([]openchoreo.WorkloadConsumerDep, error)

	// ListWorkloadEndpointsFunc mocks the ListWorkloadEndpoints method.
	ListWorkloadEndpointsFunc func(ctx context.Context, orgHandle string) ([]openchoreo.WorkloadEndpointInfo, error)

	// PatchBindingEnvironmentConfigsFunc mocks the PatchBindingEnvironmentConfigs method.
	PatchBindingEnvironmentConfigsFunc func(ctx context.Context, orgID string, bindingName string, configs map[string]string) error

	// UpdateResourceTypeFunc mocks the UpdateResourceType method.
	UpdateResourceTypeFunc func(ctx context.Context, namespace string, rt *openchoreo.ResourceType) (*openchoreo.ResourceType, error)

	// calls tracks calls to the methods.
	calls struct {
		// ApplyResource holds details about calls to the ApplyResource method.
		ApplyResource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// R is the r argument value.
			R *openchoreo.Resource
		}
		// DeleteBinding holds details about calls to the DeleteBinding method.
		DeleteBinding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// DeleteResource holds details about calls to the DeleteResource method.
		DeleteResource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// DeleteResourceType holds details about calls to the DeleteResourceType method.
		DeleteResourceType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// EnsureBinding holds details about calls to the EnsureBinding method.
		EnsureBinding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// B is the b argument value.
			B *openchoreo.ResourceReleaseBinding
		}
		// EnsureResourceType holds details about calls to the EnsureResourceType method.
		EnsureResourceType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Rt is the rt argument value.
			Rt *openchoreo.ResourceType
		}
		// GetBinding holds details about calls to the GetBinding method.
		GetBinding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// GetResource holds details about calls to the GetResource method.
		GetResource []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// GetResourceType holds details about calls to the GetResourceType method.
		GetResourceType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// ListClusterResourceTypes holds details about calls to the ListClusterResourceTypes method.
		ListClusterResourceTypes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListResourceTypes holds details about calls to the ListResourceTypes method.
		ListResourceTypes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
		}
		// ListWorkloadConsumerDeps holds details about calls to the ListWorkloadConsumerDeps method.
		ListWorkloadConsumerDeps []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgHandle is the orgHandle argument value.
			OrgHandle string
			// ProjectName is the projectName argument value.
			ProjectName string
		}
		// ListWorkloadEndpoints holds details about calls to the ListWorkloadEndpoints method.
		ListWorkloadEndpoints []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgHandle is the orgHandle argument value.
			OrgHandle string
		}
		// PatchBindingEnvironmentConfigs holds details about calls to the PatchBindingEnvironmentConfigs method.
		PatchBindingEnvironmentConfigs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgID is the orgID argument value.
			OrgID string
			// BindingName is the bindingName argument value.
			BindingName string
			// Configs is the configs argument value.
			Configs map[string]string
		}
		// UpdateResourceType holds details about calls to the UpdateResourceType method.
		UpdateResourceType []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Namespace is the namespace argument value.
			Namespace string
			// Rt is the rt argument value.
			Rt *openchoreo.ResourceType
		}
	}
	lockApplyResource                  sync.RWMutex
	lockDeleteBinding                  sync.RWMutex
	lockDeleteResource                 sync.RWMutex
	lockDeleteResourceType             sync.RWMutex
	lockEnsureBinding                  sync.RWMutex
	lockEnsureResourceType             sync.RWMutex
	lockGetBinding                     sync.RWMutex
	lockGetResource                    sync.RWMutex
	lockGetResourceType                sync.RWMutex
	lockListClusterResourceTypes       sync.RWMutex
	lockListResourceTypes              sync.RWMutex
	lockListWorkloadConsumerDeps       sync.RWMutex
	lockListWorkloadEndpoints          sync.RWMutex
	lockPatchBindingEnvironmentConfigs sync.RWMutex
	lockUpdateResourceType             sync.RWMutex
}

// ApplyResource calls ApplyResourceFunc.
func (mock *ResourceClientMock) ApplyResource(ctx context.Context, namespace string, r *openchoreo.Resource) (*openchoreo.Resource, error) {
	if mock.ApplyResourceFunc == nil {
		panic("ResourceClientMock.ApplyResourceFunc: method is nil but ResourceClient.ApplyResource was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		R         *openchoreo.Resource
	}{
		Ctx:       ctx,
		Namespace: namespace,
		R:         r,
	}
	mock.lockApplyResource.Lock()
	mock.calls.ApplyResource = append(mock.calls.ApplyResource, callInfo)
	mock.lockApplyResource.Unlock()
	return mock.ApplyResourceFunc(ctx, namespace, r)
}

// ApplyResourceCalls gets all the calls that were made to ApplyResource.
// Check the length with:
//
//	len(mockedResourceClient.ApplyResourceCalls())
func (mock *ResourceClientMock) ApplyResourceCalls() []struct {
	Ctx       context.Context
	Namespace string
	R         *openchoreo.Resource
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		R         *openchoreo.Resource
	}
	mock.lockApplyResource.RLock()
	calls = mock.calls.ApplyResource
	mock.lockApplyResource.RUnlock()
	return calls
}

// DeleteBinding calls DeleteBindingFunc.
func (mock *ResourceClientMock) DeleteBinding(ctx context.Context, namespace string, name string) error {
	if mock.DeleteBindingFunc == nil {
		panic("ResourceClientMock.DeleteBindingFunc: method is nil but ResourceClient.DeleteBinding was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Name:      name,
	}
	mock.lockDeleteBinding.Lock()
	mock.calls.DeleteBinding = append(mock.calls.DeleteBinding, callInfo)
	mock.lockDeleteBinding.Unlock()
	return mock.DeleteBindingFunc(ctx, namespace, name)
}

// DeleteBindingCalls gets all the calls that were made to DeleteBinding.
// Check the length with:
//
//	len(mockedResourceClient.DeleteBindingCalls())
func (mock *ResourceClientMock) DeleteBindingCalls() []struct {
	Ctx       context.Context
	Namespace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}
	mock.lockDeleteBinding.RLock()
	calls = mock.calls.DeleteBinding
	mock.lockDeleteBinding.RUnlock()
	return calls
}

// DeleteResource calls DeleteResourceFunc.
func (mock *ResourceClientMock) DeleteResource(ctx context.Context, namespace string, name string) error {
	if mock.DeleteResourceFunc == nil {
		panic("ResourceClientMock.DeleteResourceFunc: method is nil but ResourceClient.DeleteResource was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Name:      name,
	}
	mock.lockDeleteResource.Lock()
	mock.calls.DeleteResource = append(mock.calls.DeleteResource, callInfo)
	mock.lockDeleteResource.Unlock()
	return mock.DeleteResourceFunc(ctx, namespace, name)
}

// DeleteResourceCalls gets all the calls that were made to DeleteResource.
// Check the length with:
//
//	len(mockedResourceClient.DeleteResourceCalls())
func (mock *ResourceClientMock) DeleteResourceCalls() []struct {
	Ctx       context.Context
	Namespace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}
	mock.lockDeleteResource.RLock()
	calls = mock.calls.DeleteResource
	mock.lockDeleteResource.RUnlock()
	return calls
}

// DeleteResourceType calls DeleteResourceTypeFunc.
func (mock *ResourceClientMock) DeleteResourceType(ctx context.Context, namespace string, name string) error {
	if mock.DeleteResourceTypeFunc == nil {
		panic("ResourceClientMock.DeleteResourceTypeFunc: method is nil but ResourceClient.DeleteResourceType was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Name:      name,
	}
	mock.lockDeleteResourceType.Lock()
	mock.calls.DeleteResourceType = append(mock.calls.DeleteResourceType, callInfo)
	mock.lockDeleteResourceType.Unlock()
	return mock.DeleteResourceTypeFunc(ctx, namespace, name)
}

// DeleteResourceTypeCalls gets all the calls that were made to DeleteResourceType.
// Check the length with:
//
//	len(mockedResourceClient.DeleteResourceTypeCalls())
func (mock *ResourceClientMock) DeleteResourceTypeCalls() []struct {
	Ctx       context.Context
	Namespace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}
	mock.lockDeleteResourceType.RLock()
	calls = mock.calls.DeleteResourceType
	mock.lockDeleteResourceType.RUnlock()
	return calls
}

// EnsureBinding calls EnsureBindingFunc.
func (mock *ResourceClientMock) EnsureBinding(ctx context.Context, namespace string, b *openchoreo.ResourceReleaseBinding) (*openchoreo.ResourceReleaseBinding, error) {
	if mock.EnsureBindingFunc == nil {
		panic("ResourceClientMock.EnsureBindingFunc: method is nil but ResourceClient.EnsureBinding was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		B         *openchoreo.ResourceReleaseBinding
	}{
		Ctx:       ctx,
		Namespace: namespace,
		B:         b,
	}
	mock.lockEnsureBinding.Lock()
	mock.calls.EnsureBinding = append(mock.calls.EnsureBinding, callInfo)
	mock.lockEnsureBinding.Unlock()
	return mock.EnsureBindingFunc(ctx, namespace, b)
}

// EnsureBindingCalls gets all the calls that were made to EnsureBinding.
// Check the length with:
//
//	len(mockedResourceClient.EnsureBindingCalls())
func (mock *ResourceClientMock) EnsureBindingCalls() []struct {
	Ctx       context.Context
	Namespace string
	B         *openchoreo.ResourceReleaseBinding
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		B         *openchoreo.ResourceReleaseBinding
	}
	mock.lockEnsureBinding.RLock()
	calls = mock.calls.EnsureBinding
	mock.lockEnsureBinding.RUnlock()
	return calls
}

// EnsureResourceType calls EnsureResourceTypeFunc.
func (mock *ResourceClientMock) EnsureResourceType(ctx context.Context, namespace string, rt *openchoreo.ResourceType) (*openchoreo.ResourceType, error) {
	if mock.EnsureResourceTypeFunc == nil {
		panic("ResourceClientMock.EnsureResourceTypeFunc: method is nil but ResourceClient.EnsureResourceType was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Rt        *openchoreo.ResourceType
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Rt:        rt,
	}
	mock.lockEnsureResourceType.Lock()
	mock.calls.EnsureResourceType = append(mock.calls.EnsureResourceType, callInfo)
	mock.lockEnsureResourceType.Unlock()
	return mock.EnsureResourceTypeFunc(ctx, namespace, rt)
}

// EnsureResourceTypeCalls gets all the calls that were made to EnsureResourceType.
// Check the length with:
//
//	len(mockedResourceClient.EnsureResourceTypeCalls())
func (mock *ResourceClientMock) EnsureResourceTypeCalls() []struct {
	Ctx       context.Context
	Namespace string
	Rt        *openchoreo.ResourceType
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Rt        *openchoreo.ResourceType
	}
	mock.lockEnsureResourceType.RLock()
	calls = mock.calls.EnsureResourceType
	mock.lockEnsureResourceType.RUnlock()
	return calls
}

// GetBinding calls GetBindingFunc.
func (mock *ResourceClientMock) GetBinding(ctx context.Context, namespace string, name string) (*openchoreo.ResourceReleaseBinding, error) {
	if mock.GetBindingFunc == nil {
		panic("ResourceClientMock.GetBindingFunc: method is nil but ResourceClient.GetBinding was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Name:      name,
	}
	mock.lockGetBinding.Lock()
	mock.calls.GetBinding = append(mock.calls.GetBinding, callInfo)
	mock.lockGetBinding.Unlock()
	return mock.GetBindingFunc(ctx, namespace, name)
}

// GetBindingCalls gets all the calls that were made to GetBinding.
// Check the length with:
//
//	len(mockedResourceClient.GetBindingCalls())
func (mock *ResourceClientMock) GetBindingCalls() []struct {
	Ctx       context.Context
	Namespace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}
	mock.lockGetBinding.RLock()
	calls = mock.calls.GetBinding
	mock.lockGetBinding.RUnlock()
	return calls
}

// GetResource calls GetResourceFunc.
func (mock *ResourceClientMock) GetResource(ctx context.Context, namespace string, name string) (*openchoreo.Resource, error) {
	if mock.GetResourceFunc == nil {
		panic("ResourceClientMock.GetResourceFunc: method is nil but ResourceClient.GetResource was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Name:      name,
	}
	mock.lockGetResource.Lock()
	mock.calls.GetResource = append(mock.calls.GetResource, callInfo)
	mock.lockGetResource.Unlock()
	return mock.GetResourceFunc(ctx, namespace, name)
}

// GetResourceCalls gets all the calls that were made to GetResource.
// Check the length with:
//
//	len(mockedResourceClient.GetResourceCalls())
func (mock *ResourceClientMock) GetResourceCalls() []struct {
	Ctx       context.Context
	Namespace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}
	mock.lockGetResource.RLock()
	calls = mock.calls.GetResource
	mock.lockGetResource.RUnlock()
	return calls
}

// GetResourceType calls GetResourceTypeFunc.
func (mock *ResourceClientMock) GetResourceType(ctx context.Context, namespace string, name string) (*openchoreo.ResourceType, error) {
	if mock.GetResourceTypeFunc == nil {
		panic("ResourceClientMock.GetResourceTypeFunc: method is nil but ResourceClient.GetResourceType was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Name:      name,
	}
	mock.lockGetResourceType.Lock()
	mock.calls.GetResourceType = append(mock.calls.GetResourceType, callInfo)
	mock.lockGetResourceType.Unlock()
	return mock.GetResourceTypeFunc(ctx, namespace, name)
}

// GetResourceTypeCalls gets all the calls that were made to GetResourceType.
// Check the length with:
//
//	len(mockedResourceClient.GetResourceTypeCalls())
func (mock *ResourceClientMock) GetResourceTypeCalls() []struct {
	Ctx       context.Context
	Namespace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Name      string
	}
	mock.lockGetResourceType.RLock()
	calls = mock.calls.GetResourceType
	mock.lockGetResourceType.RUnlock()
	return calls
}

// ListClusterResourceTypes calls ListClusterResourceTypesFunc.
func (mock *ResourceClientMock) ListClusterResourceTypes(ctx context.Context) ([]openchoreo.ResourceType, error) {
	if mock.ListClusterResourceTypesFunc == nil {
		panic("ResourceClientMock.ListClusterResourceTypesFunc: method is nil but ResourceClient.ListClusterResourceTypes was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListClusterResourceTypes.Lock()
	mock.calls.ListClusterResourceTypes = append(mock.calls.ListClusterResourceTypes, callInfo)
	mock.lockListClusterResourceTypes.Unlock()
	return mock.ListClusterResourceTypesFunc(ctx)
}

// ListClusterResourceTypesCalls gets all the calls that were made to ListClusterResourceTypes.
// Check the length with:
//
//	len(mockedResourceClient.ListClusterResourceTypesCalls())
func (mock *ResourceClientMock) ListClusterResourceTypesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListClusterResourceTypes.RLock()
	calls = mock.calls.ListClusterResourceTypes
	mock.lockListClusterResourceTypes.RUnlock()
	return calls
}

// ListResourceTypes calls ListResourceTypesFunc.
func (mock *ResourceClientMock) ListResourceTypes(ctx context.Context, namespace string) ([]openchoreo.ResourceType, error) {
	if mock.ListResourceTypesFunc == nil {
		panic("ResourceClientMock.ListResourceTypesFunc: method is nil but ResourceClient.ListResourceTypes was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
	}{
		Ctx:       ctx,
		Namespace: namespace,
	}
	mock.lockListResourceTypes.Lock()
	mock.calls.ListResourceTypes = append(mock.calls.ListResourceTypes, callInfo)
	mock.lockListResourceTypes.Unlock()
	return mock.ListResourceTypesFunc(ctx, namespace)
}

// ListResourceTypesCalls gets all the calls that were made to ListResourceTypes.
// Check the length with:
//
//	len(mockedResourceClient.ListResourceTypesCalls())
func (mock *ResourceClientMock) ListResourceTypesCalls() []struct {
	Ctx       context.Context
	Namespace string
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
	}
	mock.lockListResourceTypes.RLock()
	calls = mock.calls.ListResourceTypes
	mock.lockListResourceTypes.RUnlock()
	return calls
}

// ListWorkloadConsumerDeps calls ListWorkloadConsumerDepsFunc.
func (mock *ResourceClientMock) ListWorkloadConsumerDeps(ctx context.Context, orgHandle string, projectName string) ([]openchoreo.WorkloadConsumerDep, error) {
	if mock.ListWorkloadConsumerDepsFunc == nil {
		panic("ResourceClientMock.ListWorkloadConsumerDepsFunc: method is nil but ResourceClient.ListWorkloadConsumerDeps was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgHandle   string
		ProjectName string
	}{
		Ctx:         ctx,
		OrgHandle:   orgHandle,
		ProjectName: projectName,
	}
	mock.lockListWorkloadConsumerDeps.Lock()
	mock.calls.ListWorkloadConsumerDeps = append(mock.calls.ListWorkloadConsumerDeps, callInfo)
	mock.lockListWorkloadConsumerDeps.Unlock()
	return mock.ListWorkloadConsumerDepsFunc(ctx, orgHandle, projectName)
}

// ListWorkloadConsumerDepsCalls gets all the calls that were made to ListWorkloadConsumerDeps.
// Check the length with:
//
//	len(mockedResourceClient.ListWorkloadConsumerDepsCalls())
func (mock *ResourceClientMock) ListWorkloadConsumerDepsCalls() []struct {
	Ctx         context.Context
	OrgHandle   string
	ProjectName string
} {
	var calls []struct {
		Ctx         context.Context
		OrgHandle   string
		ProjectName string
	}
	mock.lockListWorkloadConsumerDeps.RLock()
	calls = mock.calls.ListWorkloadConsumerDeps
	mock.lockListWorkloadConsumerDeps.RUnlock()
	return calls
}

// ListWorkloadEndpoints calls ListWorkloadEndpointsFunc.
func (mock *ResourceClientMock) ListWorkloadEndpoints(ctx context.Context, orgHandle string) ([]openchoreo.WorkloadEndpointInfo, error) {
	if mock.ListWorkloadEndpointsFunc == nil {
		panic("ResourceClientMock.ListWorkloadEndpointsFunc: method is nil but ResourceClient.ListWorkloadEndpoints was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OrgHandle string
	}{
		Ctx:       ctx,
		OrgHandle: orgHandle,
	}
	mock.lockListWorkloadEndpoints.Lock()
	mock.calls.ListWorkloadEndpoints = append(mock.calls.ListWorkloadEndpoints, callInfo)
	mock.lockListWorkloadEndpoints.Unlock()
	return mock.ListWorkloadEndpointsFunc(ctx, orgHandle)
}

// ListWorkloadEndpointsCalls gets all the calls that were made to ListWorkloadEndpoints.
// Check the length with:
//
//	len(mockedResourceClient.ListWorkloadEndpointsCalls())
func (mock *ResourceClientMock) ListWorkloadEndpointsCalls() []struct {
	Ctx       context.Context
	OrgHandle string
} {
	var calls []struct {
		Ctx       context.Context
		OrgHandle string
	}
	mock.lockListWorkloadEndpoints.RLock()
	calls = mock.calls.ListWorkloadEndpoints
	mock.lockListWorkloadEndpoints.RUnlock()
	return calls
}

// PatchBindingEnvironmentConfigs calls PatchBindingEnvironmentConfigsFunc.
func (mock *ResourceClientMock) PatchBindingEnvironmentConfigs(ctx context.Context, orgID string, bindingName string, configs map[string]string) error {
	if mock.PatchBindingEnvironmentConfigsFunc == nil {
		panic("ResourceClientMock.PatchBindingEnvironmentConfigsFunc: method is nil but ResourceClient.PatchBindingEnvironmentConfigs was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OrgID       string
		BindingName string
		Configs     map[string]string
	}{
		Ctx:         ctx,
		OrgID:       orgID,
		BindingName: bindingName,
		Configs:     configs,
	}
	mock.lockPatchBindingEnvironmentConfigs.Lock()
	mock.calls.PatchBindingEnvironmentConfigs = append(mock.calls.PatchBindingEnvironmentConfigs, callInfo)
	mock.lockPatchBindingEnvironmentConfigs.Unlock()
	return mock.PatchBindingEnvironmentConfigsFunc(ctx, orgID, bindingName, configs)
}

// PatchBindingEnvironmentConfigsCalls gets all the calls that were made to PatchBindingEnvironmentConfigs.
// Check the length with:
//
//	len(mockedResourceClient.PatchBindingEnvironmentConfigsCalls())
func (mock *ResourceClientMock) PatchBindingEnvironmentConfigsCalls() []struct {
	Ctx         context.Context
	OrgID       string
	BindingName string
	Configs     map[string]string
} {
	var calls []struct {
		Ctx         context.Context
		OrgID       string
		BindingName string
		Configs     map[string]string
	}
	mock.lockPatchBindingEnvironmentConfigs.RLock()
	calls = mock.calls.PatchBindingEnvironmentConfigs
	mock.lockPatchBindingEnvironmentConfigs.RUnlock()
	return calls
}

// UpdateResourceType calls UpdateResourceTypeFunc.
func (mock *ResourceClientMock) UpdateResourceType(ctx context.Context, namespace string, rt *openchoreo.ResourceType) (*openchoreo.ResourceType, error) {
	if mock.UpdateResourceTypeFunc == nil {
		panic("ResourceClientMock.UpdateResourceTypeFunc: method is nil but ResourceClient.UpdateResourceType was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Namespace string
		Rt        *openchoreo.ResourceType
	}{
		Ctx:       ctx,
		Namespace: namespace,
		Rt:        rt,
	}
	mock.lockUpdateResourceType.Lock()
	mock.calls.UpdateResourceType = append(mock.calls.UpdateResourceType, callInfo)
	mock.lockUpdateResourceType.Unlock()
	return mock.UpdateResourceTypeFunc(ctx, namespace, rt)
}

// UpdateResourceTypeCalls gets all the calls that were made to UpdateResourceType.
// Check the length with:
//
//	len(mockedResourceClient.UpdateResourceTypeCalls())
func (mock *ResourceClientMock) UpdateResourceTypeCalls() []struct {
	Ctx       context.Context
	Namespace string
	Rt        *openchoreo.ResourceType
} {
	var calls []struct {
		Ctx       context.Context
		Namespace string
		Rt        *openchoreo.ResourceType
	}
	mock.lockUpdateResourceType.RLock()
	calls = mock.calls.UpdateResourceType
	mock.lockUpdateResourceType.RUnlock()
	return calls
}
