//go:build go1.22

// Package igen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package igen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AeStudioCCScopes  aeStudioCCContextKey  = "aeStudioCC.Scopes"
	PublisherCCScopes publisherCCContextKey = "publisherCC.Scopes"
	SreHandoffScopes  sreHandoffContextKey  = "sreHandoff.Scopes"
)

// Defines values for AEStudioTurnRecordKind.
const (
	AEStudioTurnRecordKindBrowser AEStudioTurnRecordKind = "browser"
	AEStudioTurnRecordKindKickoff AEStudioTurnRecordKind = "kickoff"
	AEStudioTurnRecordKindPlan    AEStudioTurnRecordKind = "plan"
)

// Valid indicates whether the value is a known member of the AEStudioTurnRecordKind enum.
func (e AEStudioTurnRecordKind) Valid() bool {
	switch e {
	case AEStudioTurnRecordKindBrowser:
		return true
	case AEStudioTurnRecordKindKickoff:
		return true
	case AEStudioTurnRecordKindPlan:
		return true
	default:
		return false
	}
}

// Defines values for AEStudioTurnRecordReason.
const (
	AEStudioTurnRecordReasonAgentError AEStudioTurnRecordReason = "agent-error"
	AEStudioTurnRecordReasonInternal   AEStudioTurnRecordReason = "internal"
	AEStudioTurnRecordReasonShutdown   AEStudioTurnRecordReason = "shutdown"
	AEStudioTurnRecordReasonStreamDied AEStudioTurnRecordReason = "stream-died"
)

// Valid indicates whether the value is a known member of the AEStudioTurnRecordReason enum.
func (e AEStudioTurnRecordReason) Valid() bool {
	switch e {
	case AEStudioTurnRecordReasonAgentError:
		return true
	case AEStudioTurnRecordReasonInternal:
		return true
	case AEStudioTurnRecordReasonShutdown:
		return true
	case AEStudioTurnRecordReasonStreamDied:
		return true
	default:
		return false
	}
}

// Defines values for AEStudioTurnRecordStatus.
const (
	AEStudioTurnRecordStatusCompleted AEStudioTurnRecordStatus = "completed"
	AEStudioTurnRecordStatusFailed    AEStudioTurnRecordStatus = "failed"
)

// Valid indicates whether the value is a known member of the AEStudioTurnRecordStatus enum.
func (e AEStudioTurnRecordStatus) Valid() bool {
	switch e {
	case AEStudioTurnRecordStatusCompleted:
		return true
	case AEStudioTurnRecordStatusFailed:
		return true
	default:
		return false
	}
}

// Defines values for AEStudioWebhookEventResultResult.
const (
	AEStudioWebhookEventResultResultDispatched AEStudioWebhookEventResultResult = "dispatched"
	AEStudioWebhookEventResultResultDuplicate  AEStudioWebhookEventResultResult = "duplicate"
	AEStudioWebhookEventResultResultHeld       AEStudioWebhookEventResultResult = "held"
)

// Valid indicates whether the value is a known member of the AEStudioWebhookEventResultResult enum.
func (e AEStudioWebhookEventResultResult) Valid() bool {
	switch e {
	case AEStudioWebhookEventResultResultDispatched:
		return true
	case AEStudioWebhookEventResultResultDuplicate:
		return true
	case AEStudioWebhookEventResultResultHeld:
		return true
	default:
		return false
	}
}

// Defines values for IssueInfoAttentionReason.
const (
	IssueInfoAttentionReasonEscalated       IssueInfoAttentionReason = "escalated"
	IssueInfoAttentionReasonNoChangeVerdict IssueInfoAttentionReason = "no_change_verdict"
	IssueInfoAttentionReasonUnverifiedFix   IssueInfoAttentionReason = "unverified_fix"
)

// Valid indicates whether the value is a known member of the IssueInfoAttentionReason enum.
func (e IssueInfoAttentionReason) Valid() bool {
	switch e {
	case IssueInfoAttentionReasonEscalated:
		return true
	case IssueInfoAttentionReasonNoChangeVerdict:
		return true
	case IssueInfoAttentionReasonUnverifiedFix:
		return true
	default:
		return false
	}
}

// AEStudioCompletedDependency One completed stub. `definition` replaces the stub's dependency.json content; `files` land beside it in the same commit.
type AEStudioCompletedDependency struct {
	Definition string         `json:"definition"`
	Files      []AEStudioFile `json:"files"`

	// Path The stub's dependency.json path, as sent.
	Path string `json:"path"`
}

// AEStudioDependencyCompletions The stubs aep-api completed, and the warnings for every stub it touched (completed or not).
type AEStudioDependencyCompletions struct {
	Completed []AEStudioCompletedDependency `json:"completed"`
	Warnings  []AEStudioWarning             `json:"warnings"`
}

// AEStudioDependencyCompletionsRequest The dependency stub writes of one save to a project.
type AEStudioDependencyCompletionsRequest struct {
	// Project The project the save is for. It must belong to the token's org, else 404 (the same answer as an unknown project).
	Project string `json:"project"`

	// Writes At most 64 stubs, bounding the outbound registry reads and fetches one call can cause.
	Writes []AEStudioFile `json:"writes"`
}

// AEStudioFile A repo-relative file path and its UTF-8 content.
type AEStudioFile struct {
	Content string `json:"content"`
	Path    string `json:"path"`
}

// AEStudioProjectRepository A project's GitHub repository, as the AE Studio tools pod clones it.
type AEStudioProjectRepository struct {
	CloneURL      string `json:"cloneUrl"`
	DefaultBranch string `json:"defaultBranch"`

	// Owner GitHub owner (user or organization) of the repo.
	Owner string `json:"owner"`

	// Repo GitHub repository name.
	Repo string `json:"repo"`
}

// AEStudioTurnRecord One finished turn, as the ledger stores it. Idempotent on turnId.
type AEStudioTurnRecord struct {
	Author *AEStudioTurnRecordAuthor `json:"author,omitempty"`

	// BaseRef The repo snapshot sha the turn read.
	BaseRef             string                 `json:"baseRef"`
	CacheCreationTokens int64                  `json:"cacheCreationTokens"`
	CacheReadTokens     int64                  `json:"cacheReadTokens"`
	Code                string                 `json:"code,omitempty"`
	ContextTokens       int64                  `json:"contextTokens,omitempty"`
	ConversationID      openapi_types.UUID     `json:"conversationId"`
	FinishedAt          time.Time              `json:"finishedAt"`
	Flow                string                 `json:"flow"`
	InputTokens         int64                  `json:"inputTokens"`
	Kind                AEStudioTurnRecordKind `json:"kind"`
	Model               string                 `json:"model"`
	ModelHost           string                 `json:"modelHost"`
	OutputTokens        int64                  `json:"outputTokens"`

	// Project Absent on a marketplace turn.
	Project string                   `json:"project,omitempty"`
	Reason  AEStudioTurnRecordReason `json:"reason,omitempty"`

	// SkillsRef The Org skills snapshot sha the turn read.
	SkillsRef string                   `json:"skillsRef"`
	StartedAt time.Time                `json:"startedAt"`
	Status    AEStudioTurnRecordStatus `json:"status"`
	TurnID    openapi_types.UUID       `json:"turnId"`
}

// AEStudioTurnRecordKind defines model for AEStudioTurnRecord.Kind.
type AEStudioTurnRecordKind string

// AEStudioTurnRecordReason defines model for AEStudioTurnRecord.Reason.
type AEStudioTurnRecordReason string

// AEStudioTurnRecordStatus defines model for AEStudioTurnRecord.Status.
type AEStudioTurnRecordStatus string

// AEStudioTurnRecordAuthor defines model for AEStudioTurnRecordAuthor.
type AEStudioTurnRecordAuthor struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// AEStudioTurnUsageRequest The records of finished turns.
type AEStudioTurnUsageRequest struct {
	Records []AEStudioTurnRecord `json:"records"`
}

// AEStudioWarning A non-fatal note on one path (registry-copied, registry-miss, registry-unreachable, provider-document-fetched, provider-document-unavailable).
type AEStudioWarning struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Path    string `json:"path"`
}

// AEStudioWebhookEvent A GitHub webhook payload, exactly as GitHub sent it. Declares no
// properties or defaults, so validation never rewrites it, and is
// generated as json.RawMessage so the handler gets the bytes as they
// arrived.
type AEStudioWebhookEvent = json.RawMessage

// AEStudioWebhookEventResult What became of an ingested delivery.
type AEStudioWebhookEventResult struct {
	Result AEStudioWebhookEventResultResult `json:"result"`
}

// AEStudioWebhookEventResultResult defines model for AEStudioWebhookEventResult.Result.
type AEStudioWebhookEventResultResult string

// ComponentEndpoint defines model for ComponentEndpoint.
type ComponentEndpoint struct {
	Component string `json:"component"`
	URL       string `json:"url"`
}

// CreateIssueRequest Issue to file on the project's repo. dedupeKey makes creation idempotent per open issue (label-encoded), for concurrent alert handlers. componentName and actionStatuses carry the SRE incident handoff context; they do not declare issue-create outcomes.
type CreateIssueRequest struct {
	// ActionStatuses Ordered per-action statuses from the incident handoff. A null entry is meaningful and preserves the action's position when it has no status.
	ActionStatuses []*string `json:"actionStatuses,omitempty"`
	Body           string    `json:"body"`

	// ComponentName Component affected by the incident.
	ComponentName string   `json:"componentName,omitempty"`
	DedupeKey     string   `json:"dedupeKey,omitempty"`
	Labels        []string `json:"labels,omitempty"`
	Title         string   `json:"title"`
}

// CreateRcaAgentReportRequest Write-side request for a new RCA-agent alert report (issue
type CreateRcaAgentReportRequest struct {
	// Classification code-level, config-level, mixed, or none — set by the handoff agent
	Classification string     `json:"classification"`
	Component      string     `json:"component,omitempty"`
	Deployed       bool       `json:"deployed,omitempty"`
	DeployedAt     *time.Time `json:"deployedAt,omitempty"`

	// Diagnosis Full RCA diagnosis + remediation content (markdown)
	Diagnosis    string `json:"diagnosis"`
	Dispatched   bool   `json:"dispatched,omitempty"`
	IssueExcerpt string `json:"issueExcerpt,omitempty"`
	IssueNumber  *int64 `json:"issueNumber,omitempty"`
	IssueTitle   string `json:"issueTitle,omitempty"`
	IssueURL     string `json:"issueUrl,omitempty"`
	Project      string `json:"project"`
	Summary      string `json:"summary"`
	Title        string `json:"title"`
}

// Error Flat error envelope returned by every non-2xx response.
type Error struct {
	// Code Machine-readable error code (stable slug).
	Code string `json:"code"`

	// Details Field-level details for validation errors.
	Details []ErrorDetail `json:"details,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// IssueInfo One issue from list/search. Field names are CAPITALIZED on the wire (historical shape the deployed aep-mcp-server parses — do not "fix" without a coordinated MCP-server release).
type IssueInfo struct {
	Body   string   `json:"Body"`
	Labels []string `json:"Labels"`
	Number int64    `json:"Number"`
	State  string   `json:"State"`

	// StateReason Provider-supplied reason for the issue state, when available.
	StateReason string `json:"StateReason,omitempty"`
	Title       string `json:"Title"`
	URL         string `json:"URL"`

	// AttentionReason Console attention state. Omitted when the issue needs no attention.
	AttentionReason IssueInfoAttentionReason `json:"attentionReason,omitempty"`
}

// IssueInfoAttentionReason Console attention state. Omitted when the issue needs no attention.
type IssueInfoAttentionReason string

// IssueResult Server-derived issue-create outcome. deduped=true means an open issue with the same dedupeKey already existed — number/url refer to it. Callers never supply classification, suppression, reopening, adoption, or recurrence outcomes.
type IssueResult struct {
	// Adopted True when the server adopted the incident into an existing issue.
	Adopted bool `json:"adopted,omitempty"`

	// AdoptionError Server-derived reason adoption did not complete, when present.
	AdoptionError string `json:"adoptionError,omitempty"`

	// Classification Server-derived incident classification.
	Classification string `json:"classification,omitempty"`
	Deduped        bool   `json:"deduped,omitempty"`
	NodeID         string `json:"nodeId"`
	Number         int64  `json:"number"`

	// RecurrenceCount Server-derived count of recorded recurrences for this incident.
	RecurrenceCount int64 `json:"recurrenceCount,omitempty"`

	// Reopened True when the server reopened a matching closed issue.
	Reopened bool `json:"reopened,omitempty"`

	// Suppressed True when the server suppressed creation for this incident.
	Suppressed bool   `json:"suppressed,omitempty"`
	URL        string `json:"url"`
}

// RcaAgentReport An RCA report from the OpenChoreo SRE/RCA-agent handoff (console issues
type RcaAgentReport struct {
	// Classification code-level, config-level, mixed, or none — set by the handoff agent
	Classification string    `json:"classification"`
	Component      string    `json:"component,omitempty"`
	CreatedAt      time.Time `json:"createdAt"`

	// Deployed Whether the resulting fix has been deployed (Verify Fix threshold, not merely PR-merged)
	Deployed   bool       `json:"deployed"`
	DeployedAt *time.Time `json:"deployedAt,omitempty"`

	// Diagnosis Full RCA diagnosis + remediation content (markdown)
	Diagnosis string `json:"diagnosis"`

	// Dispatched Whether the coding agent has been dispatched for the linked issue (false in issue-only/manual-dispatch mode until a human dispatches)
	Dispatched bool   `json:"dispatched"`
	ID         string `json:"id"`

	// IssueExcerpt Short excerpt of the linked GitHub issue; absent when no issue was created
	IssueExcerpt string `json:"issueExcerpt,omitempty"`

	// IssueNumber GitHub issue number created by the handoff; also the Task key (see /projects/{projectName}/tasks/{issueNumber}); absent when the handoff was config-only
	IssueNumber *int64 `json:"issueNumber,omitempty"`
	IssueTitle  string `json:"issueTitle,omitempty"`
	IssueURL    string `json:"issueUrl,omitempty"`
	Project     string `json:"project"`

	// Summary Short RCA summary; the console truncates this further for list rows
	Summary string `json:"summary"`
	Title   string `json:"title"`
}

// ValidationContextResponse The deployed endpoints a validation run drives. Generated as igen.ValidationContextResponse (no x-go-type) — igen must stay a leaf, so the edge's internal handler projects the delivery domain's own struct onto this wire shape (the same decoupling as every wire projection here).
// It carries no oracle path; the runner already knows where the oracle is.
type ValidationContextResponse struct {
	Endpoints []ComponentEndpoint `json:"endpoints"`
}

// aeStudioCCContextKey is the context key for aeStudioCC security scheme
type aeStudioCCContextKey string

// publisherCCContextKey is the context key for publisherCC security scheme
type publisherCCContextKey string

// sreHandoffContextKey is the context key for sreHandoff security scheme
type sreHandoffContextKey string

// IngestWebhookEventParams defines parameters for IngestWebhookEvent.
type IngestWebhookEventParams struct {
	// XGitHubDelivery GitHub's delivery id (X-GitHub-Delivery), the dedup key.
	XGitHubDelivery string `json:"X-GitHub-Delivery"`

	// XGitHubEvent GitHub's event name (X-GitHub-Event).
	XGitHubEvent string `json:"X-GitHub-Event"`
}

// SreListIssuesParams defines parameters for SreListIssues.
type SreListIssuesParams struct {
	// Labels Comma-separated GitHub labels to filter by
	Labels string `form:"labels,omitempty" json:"labels,omitempty"`

	// Q Keyword search over issue title/body, ranked by distinct-term overlap (title weighted double), capped at 25. Recall-biased — used to surface related issues before filing a new one.
	Q string `form:"q,omitempty" json:"q,omitempty"`
}

// CompleteAeStudioDependenciesJSONRequestBody defines body for CompleteAeStudioDependencies for application/json ContentType.
type CompleteAeStudioDependenciesJSONRequestBody = AEStudioDependencyCompletionsRequest

// RecordTurnUsageJSONRequestBody defines body for RecordTurnUsage for application/json ContentType.
type RecordTurnUsageJSONRequestBody = AEStudioTurnUsageRequest

// IngestWebhookEventJSONRequestBody defines body for IngestWebhookEvent for application/json ContentType.
type IngestWebhookEventJSONRequestBody = AEStudioWebhookEvent

// SreCreateIssueJSONRequestBody defines body for SreCreateIssue for application/json ContentType.
type SreCreateIssueJSONRequestBody = CreateIssueRequest

// SreCreateRcaReportJSONRequestBody defines body for SreCreateRcaReport for application/json ContentType.
type SreCreateRcaReportJSONRequestBody = CreateRcaAgentReportRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Complete dependency stubs from a save (AE Studio tools pod)
	// (POST /ae-studio/dependency-completions)
	CompleteAeStudioDependencies(w http.ResponseWriter, r *http.Request)
	// Resolve a project to its GitHub repository (AE Studio tools pod)
	// (GET /ae-studio/projects/{projectName}/repository)
	GetAeStudioProjectRepository(w http.ResponseWriter, r *http.Request, projectName string)
	// Resolve the org's skills repository (AE Studio tools pod)
	// (GET /ae-studio/skills/repository)
	GetAeStudioSkillsRepository(w http.ResponseWriter, r *http.Request)
	// Record finished turns (AE Studio tools pod)
	// (POST /ae-studio/turn-usage)
	RecordTurnUsage(w http.ResponseWriter, r *http.Request)
	// Ingest one verified GitHub webhook delivery (AE Studio tools pod)
	// (POST /ae-studio/webhook-events)
	IngestWebhookEvent(w http.ResponseWriter, r *http.Request, params IngestWebhookEventParams)
	// Fetch a validation run's deployed endpoints (runner callback)
	// (GET /runs/{cycleId}/validation-context)
	RunnerValidationContext(w http.ResponseWriter, r *http.Request, cycleID string)
	// List/search GitHub issues on a project's repo (SRE handoff)
	// (GET /sre/projects/{projectName}/issues)
	SreListIssues(w http.ResponseWriter, r *http.Request, projectName string, params SreListIssuesParams)
	// Create a GitHub issue on a project's repo (SRE handoff)
	// (POST /sre/projects/{projectName}/issues)
	SreCreateIssue(w http.ResponseWriter, r *http.Request, projectName string)
	// Record a new RCA-agent alert report (SRE handoff)
	// (POST /sre/rca-reports)
	SreCreateRcaReport(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CompleteAeStudioDependencies operation middleware
func (siw *ServerInterfaceWrapper) CompleteAeStudioDependencies(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AeStudioCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteAeStudioDependencies(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAeStudioProjectRepository operation middleware
func (siw *ServerInterfaceWrapper) GetAeStudioProjectRepository(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectName" -------------
	var projectName string

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", r.PathValue("projectName"), &projectName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AeStudioCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAeStudioProjectRepository(w, r, projectName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAeStudioSkillsRepository operation middleware
func (siw *ServerInterfaceWrapper) GetAeStudioSkillsRepository(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AeStudioCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAeStudioSkillsRepository(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordTurnUsage operation middleware
func (siw *ServerInterfaceWrapper) RecordTurnUsage(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AeStudioCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordTurnUsage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestWebhookEvent operation middleware
func (siw *ServerInterfaceWrapper) IngestWebhookEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, AeStudioCCScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params IngestWebhookEventParams

	headers := r.Header

	// ------------- Required header parameter "X-GitHub-Delivery" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-GitHub-Delivery")]; found {
		var XGitHubDelivery string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-GitHub-Delivery", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-GitHub-Delivery", valueList[0], &XGitHubDelivery, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-GitHub-Delivery", Err: err})
			return
		}

		params.XGitHubDelivery = XGitHubDelivery

	} else {
		err := fmt.Errorf("Header parameter X-GitHub-Delivery is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-GitHub-Delivery", Err: err})
		return
	}

	// ------------- Required header parameter "X-GitHub-Event" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-GitHub-Event")]; found {
		var XGitHubEvent string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-GitHub-Event", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-GitHub-Event", valueList[0], &XGitHubEvent, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-GitHub-Event", Err: err})
			return
		}

		params.XGitHubEvent = XGitHubEvent

	} else {
		err := fmt.Errorf("Header parameter X-GitHub-Event is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-GitHub-Event", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestWebhookEvent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunnerValidationContext operation middleware
func (siw *ServerInterfaceWrapper) RunnerValidationContext(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "cycleId" -------------
	var cycleID string

	err = runtime.BindStyledParameterWithOptions("simple", "cycleId", r.PathValue("cycleId"), &cycleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cycleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, PublisherCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunnerValidationContext(w, r, cycleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SreListIssues operation middleware
func (siw *ServerInterfaceWrapper) SreListIssues(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectName" -------------
	var projectName string

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", r.PathValue("projectName"), &projectName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SreHandoffScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SreListIssuesParams

	// ------------- Optional query parameter "labels" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "labels", r.URL.Query(), &params.Labels, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "labels"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "labels", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SreListIssues(w, r, projectName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SreCreateIssue operation middleware
func (siw *ServerInterfaceWrapper) SreCreateIssue(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectName" -------------
	var projectName string

	err = runtime.BindStyledParameterWithOptions("simple", "projectName", r.PathValue("projectName"), &projectName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SreHandoffScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SreCreateIssue(w, r, projectName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SreCreateRcaReport operation middleware
func (siw *ServerInterfaceWrapper) SreCreateRcaReport(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SreHandoffScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SreCreateRcaReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/ae-studio/dependency-completions", wrapper.CompleteAeStudioDependencies)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ae-studio/projects/{projectName}/repository", wrapper.GetAeStudioProjectRepository)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ae-studio/skills/repository", wrapper.GetAeStudioSkillsRepository)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/ae-studio/turn-usage", wrapper.RecordTurnUsage)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/ae-studio/webhook-events", wrapper.IngestWebhookEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/runs/{cycleId}/validation-context", wrapper.RunnerValidationContext)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sre/projects/{projectName}/issues", wrapper.SreListIssues)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sre/projects/{projectName}/issues", wrapper.SreCreateIssue)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sre/rca-reports", wrapper.SreCreateRcaReport)

	return m
}

type CompleteAeStudioDependenciesRequestObject struct {
	Body *CompleteAeStudioDependenciesJSONRequestBody
}

type CompleteAeStudioDependenciesResponseObject interface {
	VisitCompleteAeStudioDependenciesResponse(w http.ResponseWriter) error
}

type CompleteAeStudioDependencies200JSONResponse AEStudioDependencyCompletions

func (response CompleteAeStudioDependencies200JSONResponse) VisitCompleteAeStudioDependenciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteAeStudioDependenciesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CompleteAeStudioDependenciesdefaultJSONResponse) VisitCompleteAeStudioDependenciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAeStudioProjectRepositoryRequestObject struct {
	ProjectName string `json:"projectName"`
}

type GetAeStudioProjectRepositoryResponseObject interface {
	VisitGetAeStudioProjectRepositoryResponse(w http.ResponseWriter) error
}

type GetAeStudioProjectRepository200JSONResponse AEStudioProjectRepository

func (response GetAeStudioProjectRepository200JSONResponse) VisitGetAeStudioProjectRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAeStudioProjectRepositorydefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetAeStudioProjectRepositorydefaultJSONResponse) VisitGetAeStudioProjectRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAeStudioSkillsRepositoryRequestObject struct {
}

type GetAeStudioSkillsRepositoryResponseObject interface {
	VisitGetAeStudioSkillsRepositoryResponse(w http.ResponseWriter) error
}

type GetAeStudioSkillsRepository200JSONResponse AEStudioProjectRepository

func (response GetAeStudioSkillsRepository200JSONResponse) VisitGetAeStudioSkillsRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAeStudioSkillsRepository404JSONResponse Error

func (response GetAeStudioSkillsRepository404JSONResponse) VisitGetAeStudioSkillsRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAeStudioSkillsRepositorydefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetAeStudioSkillsRepositorydefaultJSONResponse) VisitGetAeStudioSkillsRepositoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RecordTurnUsageRequestObject struct {
	Body *RecordTurnUsageJSONRequestBody
}

type RecordTurnUsageResponseObject interface {
	VisitRecordTurnUsageResponse(w http.ResponseWriter) error
}

type RecordTurnUsage202Response struct {
}

func (response RecordTurnUsage202Response) VisitRecordTurnUsageResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type RecordTurnUsage404JSONResponse Error

func (response RecordTurnUsage404JSONResponse) VisitRecordTurnUsageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RecordTurnUsagedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RecordTurnUsagedefaultJSONResponse) VisitRecordTurnUsageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type IngestWebhookEventRequestObject struct {
	Params IngestWebhookEventParams
	Body   *IngestWebhookEventJSONRequestBody
}

type IngestWebhookEventResponseObject interface {
	VisitIngestWebhookEventResponse(w http.ResponseWriter) error
}

type IngestWebhookEvent200JSONResponse AEStudioWebhookEventResult

func (response IngestWebhookEvent200JSONResponse) VisitIngestWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type IngestWebhookEvent202JSONResponse AEStudioWebhookEventResult

func (response IngestWebhookEvent202JSONResponse) VisitIngestWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type IngestWebhookEvent404JSONResponse Error

func (response IngestWebhookEvent404JSONResponse) VisitIngestWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type IngestWebhookEventdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response IngestWebhookEventdefaultJSONResponse) VisitIngestWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerValidationContextRequestObject struct {
	CycleID string `json:"cycleId"`
}

type RunnerValidationContextResponseObject interface {
	VisitRunnerValidationContextResponse(w http.ResponseWriter) error
}

type RunnerValidationContext200JSONResponse ValidationContextResponse

func (response RunnerValidationContext200JSONResponse) VisitRunnerValidationContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerValidationContextdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RunnerValidationContextdefaultJSONResponse) VisitRunnerValidationContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SreListIssuesRequestObject struct {
	ProjectName string `json:"projectName"`
	Params      SreListIssuesParams
}

type SreListIssuesResponseObject interface {
	VisitSreListIssuesResponse(w http.ResponseWriter) error
}

type SreListIssues200JSONResponse []IssueInfo

func (response SreListIssues200JSONResponse) VisitSreListIssuesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SreListIssuesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SreListIssuesdefaultJSONResponse) VisitSreListIssuesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SreCreateIssueRequestObject struct {
	ProjectName string `json:"projectName"`
	Body        *SreCreateIssueJSONRequestBody
}

type SreCreateIssueResponseObject interface {
	VisitSreCreateIssueResponse(w http.ResponseWriter) error
}

type SreCreateIssue200JSONResponse IssueResult

func (response SreCreateIssue200JSONResponse) VisitSreCreateIssueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SreCreateIssuedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SreCreateIssuedefaultJSONResponse) VisitSreCreateIssueResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SreCreateRcaReportRequestObject struct {
	Body *SreCreateRcaReportJSONRequestBody
}

type SreCreateRcaReportResponseObject interface {
	VisitSreCreateRcaReportResponse(w http.ResponseWriter) error
}

type SreCreateRcaReport201JSONResponse RcaAgentReport

func (response SreCreateRcaReport201JSONResponse) VisitSreCreateRcaReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type SreCreateRcaReportdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SreCreateRcaReportdefaultJSONResponse) VisitSreCreateRcaReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Complete dependency stubs from a save (AE Studio tools pod)
	// (POST /ae-studio/dependency-completions)
	CompleteAeStudioDependencies(ctx context.Context, request CompleteAeStudioDependenciesRequestObject) (CompleteAeStudioDependenciesResponseObject, error)
	// Resolve a project to its GitHub repository (AE Studio tools pod)
	// (GET /ae-studio/projects/{projectName}/repository)
	GetAeStudioProjectRepository(ctx context.Context, request GetAeStudioProjectRepositoryRequestObject) (GetAeStudioProjectRepositoryResponseObject, error)
	// Resolve the org's skills repository (AE Studio tools pod)
	// (GET /ae-studio/skills/repository)
	GetAeStudioSkillsRepository(ctx context.Context, request GetAeStudioSkillsRepositoryRequestObject) (GetAeStudioSkillsRepositoryResponseObject, error)
	// Record finished turns (AE Studio tools pod)
	// (POST /ae-studio/turn-usage)
	RecordTurnUsage(ctx context.Context, request RecordTurnUsageRequestObject) (RecordTurnUsageResponseObject, error)
	// Ingest one verified GitHub webhook delivery (AE Studio tools pod)
	// (POST /ae-studio/webhook-events)
	IngestWebhookEvent(ctx context.Context, request IngestWebhookEventRequestObject) (IngestWebhookEventResponseObject, error)
	// Fetch a validation run's deployed endpoints (runner callback)
	// (GET /runs/{cycleId}/validation-context)
	RunnerValidationContext(ctx context.Context, request RunnerValidationContextRequestObject) (RunnerValidationContextResponseObject, error)
	// List/search GitHub issues on a project's repo (SRE handoff)
	// (GET /sre/projects/{projectName}/issues)
	SreListIssues(ctx context.Context, request SreListIssuesRequestObject) (SreListIssuesResponseObject, error)
	// Create a GitHub issue on a project's repo (SRE handoff)
	// (POST /sre/projects/{projectName}/issues)
	SreCreateIssue(ctx context.Context, request SreCreateIssueRequestObject) (SreCreateIssueResponseObject, error)
	// Record a new RCA-agent alert report (SRE handoff)
	// (POST /sre/rca-reports)
	SreCreateRcaReport(ctx context.Context, request SreCreateRcaReportRequestObject) (SreCreateRcaReportResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CompleteAeStudioDependencies operation middleware
func (sh *strictHandler) CompleteAeStudioDependencies(w http.ResponseWriter, r *http.Request) {
	var request CompleteAeStudioDependenciesRequestObject

	var body CompleteAeStudioDependenciesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteAeStudioDependencies(ctx, request.(CompleteAeStudioDependenciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteAeStudioDependencies")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteAeStudioDependenciesResponseObject); ok {
		if err := validResponse.VisitCompleteAeStudioDependenciesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAeStudioProjectRepository operation middleware
func (sh *strictHandler) GetAeStudioProjectRepository(w http.ResponseWriter, r *http.Request, projectName string) {
	var request GetAeStudioProjectRepositoryRequestObject

	request.ProjectName = projectName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAeStudioProjectRepository(ctx, request.(GetAeStudioProjectRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAeStudioProjectRepository")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAeStudioProjectRepositoryResponseObject); ok {
		if err := validResponse.VisitGetAeStudioProjectRepositoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAeStudioSkillsRepository operation middleware
func (sh *strictHandler) GetAeStudioSkillsRepository(w http.ResponseWriter, r *http.Request) {
	var request GetAeStudioSkillsRepositoryRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAeStudioSkillsRepository(ctx, request.(GetAeStudioSkillsRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAeStudioSkillsRepository")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAeStudioSkillsRepositoryResponseObject); ok {
		if err := validResponse.VisitGetAeStudioSkillsRepositoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RecordTurnUsage operation middleware
func (sh *strictHandler) RecordTurnUsage(w http.ResponseWriter, r *http.Request) {
	var request RecordTurnUsageRequestObject

	var body RecordTurnUsageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RecordTurnUsage(ctx, request.(RecordTurnUsageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RecordTurnUsage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RecordTurnUsageResponseObject); ok {
		if err := validResponse.VisitRecordTurnUsageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IngestWebhookEvent operation middleware
func (sh *strictHandler) IngestWebhookEvent(w http.ResponseWriter, r *http.Request, params IngestWebhookEventParams) {
	var request IngestWebhookEventRequestObject

	request.Params = params

	var body IngestWebhookEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IngestWebhookEvent(ctx, request.(IngestWebhookEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IngestWebhookEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IngestWebhookEventResponseObject); ok {
		if err := validResponse.VisitIngestWebhookEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunnerValidationContext operation middleware
func (sh *strictHandler) RunnerValidationContext(w http.ResponseWriter, r *http.Request, cycleID string) {
	var request RunnerValidationContextRequestObject

	request.CycleID = cycleID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunnerValidationContext(ctx, request.(RunnerValidationContextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunnerValidationContext")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunnerValidationContextResponseObject); ok {
		if err := validResponse.VisitRunnerValidationContextResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SreListIssues operation middleware
func (sh *strictHandler) SreListIssues(w http.ResponseWriter, r *http.Request, projectName string, params SreListIssuesParams) {
	var request SreListIssuesRequestObject

	request.ProjectName = projectName
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SreListIssues(ctx, request.(SreListIssuesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SreListIssues")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SreListIssuesResponseObject); ok {
		if err := validResponse.VisitSreListIssuesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SreCreateIssue operation middleware
func (sh *strictHandler) SreCreateIssue(w http.ResponseWriter, r *http.Request, projectName string) {
	var request SreCreateIssueRequestObject

	request.ProjectName = projectName

	var body SreCreateIssueJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SreCreateIssue(ctx, request.(SreCreateIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SreCreateIssue")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SreCreateIssueResponseObject); ok {
		if err := validResponse.VisitSreCreateIssueResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SreCreateRcaReport operation middleware
func (sh *strictHandler) SreCreateRcaReport(w http.ResponseWriter, r *http.Request) {
	var request SreCreateRcaReportRequestObject

	var body SreCreateRcaReportJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SreCreateRcaReport(ctx, request.(SreCreateRcaReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SreCreateRcaReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SreCreateRcaReportResponseObject); ok {
		if err := validResponse.VisitSreCreateRcaReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1HztcuO4cvatdOk9VSO9IWXv7JytxFOplNfjOevsx0zZs2dTWU1GENmSsCYBLgBa1plyVS4iV5grSXUD",
	"ICmJsi3v1+wvWyIINIDuB083uvVxkOmy0gqVs4OTjwObLbEU/O/p+ZWrc6nPdFkV6DB/hRWqHFW2psci",
	"z6WTWonirdEVGifRDk7morCYDHK0mZEVPR+cDN4ohCz2AtbVszFMc5xLxT1MwWBViAwtuCXy82cW8ma0",
	"8U9WK8i0cqjcS5jOZYF2CoVQOczQyhxBOpDKvy1KHqyUbjxIBlVHto+Ddkz65NYVDk4G1hmpFoO7ZMAd",
	"0xPpsOR//mJwPjgZ/L+jdpWOwhIdxfV5LQukt0N3whixps+VcEs/aHct3u2fIb2QgLBgUbHwWwLeJQOD",
	"P9fSYD44+dH3n3TnFGfwvnlVz37CzJE0Udp2E8O+Sq3sgfsZ52BBYJWKSra7mwDtCm3EShgl1cLCXBvA",
	"GzRrfoe2yuk6W2IOw1YptAGl3Wh3y5omB+9Ln972bFOU8+D+f/Av7va5tU/tDDqDHbxFl/hzjdY9Yada",
	"NfMbsDLSoQU9B63IXm4QnAYBldEkye4WhAf9uhweBtu7QZC842O4cFDW1sEMC60WNAQ1cfoa1TML2iwS",
	"wMIivDh+AcPGcoWyKzRkBEJBra6VXqk4htcO4RwaGv2/fhTpP47Tf3k/DP+k7z8eJ198dhe/H/3bX3aN",
	"KBn4+e/O5tRBqa2DL1545U5gpmuVSxJ+iaBrx5/B4EJaZ9ZgUOSW9X2OLlvSmhLQiaKATCjIRG2RRH4S",
	"mpTi9sK/98WLZFBKFT599oC2xc1q5nmfpvFgh2nUKYG1Tg0WwskbBEIcRi5eCOksfP/udfrPEa77DJof",
	"9AJwhMxHAV/s6L4JvvWrcYmVttJpsz54tmE9n1n4m3Rf1TOevu+LsZpU4/Qc/HDgtC4sVDqHrNAKLfSd",
	"Qvzoe1P0LkGOc1EX7ksjVLbsbaFXCs2u+gbx+CkMa4uGQFWbhVDyH4IajcjmSV6awrjPNOjB3p7biYMS",
	"JT58QHlBQ6/bM0vaZbhvA9/VRl1ipk3+BM5BB6Olg8bVRjW7VWC+QAPWaeM3CC5yLCtNygRaceOLfHfb",
	"RO2W2jzWjlvBT/17yeA2XeiUZpraa1mluvJTSSstlaMt5YncJYOZsHhJQ/QBLq0mWCUqu9QO7FJ4XK2N",
	"YkDq3ddMZEs8M8hq8I4gmGc016YUbnAykMp98aJ9kcRZoGnevESRH/aWzrFXd9lmb92BnakbNJZlv8g3",
	"XqprmffNN278qdtonguHqZMl9r5T6FWvzFJV9WESX0vFcqKqSzKEmdEry6ZwLbNrPZ+TbhVCdTS/Ha7U",
	"OfZDAz/5Stt+7NS1O1TOvQf76cwGYxBQCnONjvk5a9ke4BDWk+o4Z7FA5VI0hlXfOoOiTHPJLMgua5fr",
	"FRFW1nwlit6lsNeyKOxeS3hjFuCbHGoP1gnjDlMP64SrbXeGXV43F7LAvHcSHk4eobZb6Bne29H/oF5B",
	"YRvBWtTorlt3qhtmEfWsq1Wbqr6lUbtQ0A8rjwPz0wZL74X0TQCWea/i02H0MGngFeemD0n4vRULfDrd",
	"NjxB5tcb54/dPVFC04M9j86huMEUPzs+PoQqxuHvW5Do5BxKm5RW6Vw4UZBbh4QkxI2ZJw4jgU4zXUly",
	"GZsvSmlt52OtDIpsKWYFJkTEbmSOJs11VpcELp51532PaiVuhCzozV6fcs/xVKKlzf81uGlOKBL7u3eF",
	"cbbU+vr8JpDi7ZUM7Gvlm0El1oUWeQJ4KzJXrInVhCaM2cRnXmFWCCI3Sk9UO3Xig4GE2QSshhtRyJyN",
	"FxR56GAwOIfSeUde2olaoEIjyEkXFn6yWo0vxepbPzPqheB2KVReoIEFOk+yZmvqxjOu9UQJY+QNdsE4",
	"LESHFQ1OBlu971umS7R1caht/rAU5Ixm5GXqObmXUi3Q0rxyLOQNmnWfhcaRIurn0laC9W6QDJZY0J+8",
	"rgqZCYc9B8COzXGHfQpxFg3+XOVMCQ+ExwYwetW37vU3ekIVvgv/Qq+YhPd4YW39RJDkV8Fp7zpqH7Zr",
	"3Sx2TiDHvK7wa1xDKa7RQhZOGZAtV6/IxalQgeQeh4WYYZGiIuPLRwkHnjKtstoYai4KNC5qqh1DM9nv",
	"fOAhB5HREFd8oNKYwpg1S3d1eQ5SZTKnfqgHPZ9D4LIvWcUh14R0kHvT8yKlLDWHDjJdYs8JsDnirvm/",
	"MTkazGmqqW8LNoo3N7pk6bYlG8MpqLooAJUza5AWShSE4vO64HlWBi2amxBv9f0+I7fV8h7CakmLSv0R",
	"hIQRNyIZ1D2B6+DEmRp7WM+eBk3Ubabz9R4PobMruwvSGAmI+Rwzst7ZemMVeglfo069Y7LibB7DB0/I",
	"SVc8gob4ZmH++83rMhOnC0a6Shv3NDv7gaA85fC48R2wRQhQuILLs9OUKXowC8MDwZD1tidiIayVc8K4",
	"EDvfHIosLi3wBouEzGIuF/FTKW/phObwrkL43//+H7Do4p5FU2JJeh3XezEtx6rQa+zSwpnWBQrVfXoP",
	"y79fjTfPpv9P74zf0YvUuRQLpa3ssdnXZHqXZ6fQtIF/AoMl5tJDWAhcwZBcK/KDRr0q2x40vdPjnTq/",
	"zdBU/avDDb6ry5mPFu34g3smH/3Drdn7t2K37/Zoe3i8L7jVcTh3Hay6LIXpN9BHGlcb+4xmFjtNtlW4",
	"u4N9ZnjOjuthBve6EA7Y4wVUN1joiiyPuL9HKX8JQsz4+e0tGLSVVj5C3E9PN3v/VmRLqTAlp5a2LYxE",
	"jWFoHX9li3ox2gOATsiiT1slFrm3VgiNGCY63JAHso+OZPPSveKu+u5bOhx7U5Kv6lKo7emF1g8HGx/B",
	"uLuCHUat5rRIB3oMW/L5Lu4XkJnRhZrrJ8Q6PQdiTlBI644sCpMtx8D7ywFbC0RMzk7fXrw7/ebiP89f",
	"Re61kgZhuJTWaSMzUYBdigr5UcRQvugrsypl3mCgEoYoCMF5ID6TwVzeTgawkm6pawcCMq1NLhV7Dt+e",
	"vY2vGixQ2D637Mt9nOCbX+F8vgcIdwNjRMj64Y2fXDbRrs19eBv9UFtXVSExBx8XY4NijsKbRHwKE8+y",
	"Gjd1/OBxdJcM9sPu95ff9H4vHB01Uqt9Mp9pZXWB0DT04o3hTSkdbR2L2QqvEHNmhc0LJHn0jmp1g0bO",
	"JeYf5vKWpqQ/ZEuhFvjhBk0uGZzRZqIgtXjYXQq7FmeeeB3x043b1OjHXpN6kr94xeqa5sieay+hj25K",
	"/q+0X8yy+d6y45SQObR5Ca1XIwoCujXgrWQXlCxJ8WSPalOAwTka8pHInT8TBXkswUdn3VrD5nmW8NcG",
	"reUPBkkEqRYJiNzfMzAHM+idoexen4Te8KxjK7pFk2zUIZhzaL3piEjlNC0Ez06qhV+MDoh3eEwUsDlx",
	"792GYFDxJchlzvATg7HBrNjD8b7Ag0b1ELndVoQ4yc337nE79hA4pXO82BPSPASs2k0903VfDGlrAhm1",
	"Aj0PkUpe1NiDDVAl7YY/9SgpSOUerTaxOV8wOGI2C8gKbaOl9etKVPJHD9O+0EYQeme4O9ajAiYq4hO1",
	"bra0D4g2PbpD46mKHYrgpDWO/5sK1dlSG9RwdXl+1Pp00a8aZgHdeU3tn8Wv8yh70PVM1xXcjvuhW6IJ",
	"F990EJCuzeUthzdmiKplOcO/0+m1htfyFtzSoF3qIk8YYEo0WKzh7WVaollgPupVmkf4nJ+uj7l/3TLN",
	"aTBRueKyNW83BKeQ6jqaMAxZl0GGszDVqlgflULVokjju1CS/1IrJwsQsCQXoO3X9i/ynnugbYd4CwSX",
	"ZDroH8dEiCBuiJ9zBy9B+MtPhhKl4zkuQgwSey+ct3zt3vyJwJ+4Uexry2BegihCRP2dsNdwjWsYWkQ4",
	"Cq6tPfoY/vtOlHh35IS9tkcfO8PfjTZn0DVHnoQ3Y9qLRwD7HxgE6Ns+0vjQ5GVQTI9vztQqE44jmtLC",
	"vDasu6SW5A2B0Svbt2+PDCzw5WEbXWjx6cBIQ7J5fdCAVt+B8ffGAT/zgebLEDB4WgqgBzgMVwsWRNfD",
	"N7WCnNiBHcPfutc9coFqvFcSGCoNjYKM+BSgN3zin3ViDQIKFPMk3hNhvsBndPL6W//m3iiqd3A6/XUM",
	"5LoUkrMFV+SWmDpzoBVnEkrr3Vbvqg47DDvTdVUwWtkQceGGYQSa7RINjsYTdeE4xC/5ogy0EVlIZfO6",
	"ZWqliOAGpn6t9MqSTRnvGof2sodBN6v86Jvd3bufh7JK2zF2lYcMiSiddOsrGiDwegx5sWf0aYbCoHkd",
	"7f/ff3g32NWcWuWEVYVE5cj3IbYkRWF9GmdEUW0Wz2wnCc63n6ihwNTyV+mkPj7+PNNmwf/gKIElFox+",
	"0tm+/LmXsWeQXim0wolyS+FC9/R9Q2A54fQdtyLXqBHU329EKY5AV3aiRJZhxaSPV58PF16MFiCWzlUM",
	"VfWskHaJ5uA1q9CkJH3Tw95VfIwc1uBXHsN7kNEJJ7NmwKvL8wbvfXcwvLo8//DV6Xev3rx+/eHdm6/P",
	"vxslWwGdh4W440yoeU96YMgB75o1dSozTJ1Ow79gazMXGY7hgsCnziV7odJC6eOaNpko7+B2cP2Eo6W8",
	"hlkS/N+FcLgS61TkN2RxFvMxnLOdkwkKf5c1UU4sLIe9WMMydqFheMk2nbQal9CCjRp8shVmMa+XjF1P",
	"FL1K/4qOJy5qt6RNpCPHu/gC9u78RO01oGHAGF3ZUdKxpb2Gc19fm3rOpjBihj60BjvfhSKLB7SGDZCM",
	"helyMERRrMTaQvQkG0ckBn06phe3i9pMVLyA4gSj8URNVLjT8kHJcBTRmbMQUlnnEZ53g6s8dL5OM1FV",
	"/iq03emJGn4G38ovCUlCasMIZjjXBkGodXO+mNrn34TzfnB6/hYuorZePb+C07cXg2Rwg8Z6pf5sfDw+",
	"5rS6CpWo5OBk8Pn4ePy5z0BfMqAetSve5tin2WZZRRXy9XYP5W3Y7OQOs8r5Q46DhD6zPh5WYqK2cvpP",
	"QLRp6ZzkP5watLo2GY4NzqfkwzRpMiNSCsGZIfyZnQUjMsf2wqg8pWeohMpw7Lv53hRTr+pKkwuwhDXS",
	"TrYVIJUMF8peEr63jkK0qkKaFEUl7ZyomDwf0gBYpGcWYi4PDAmAbOINKoOlts4m8Ffadm+4Ar6//Gai",
	"sqW2qEh6TmkDn75Gahs00acLRcpNC83nCfl41mu735KFdB1FDgfLxknEmNLsfjyRvB1KS+reHkw+kWYa",
	"+Mc0FkVwN3rOPTXsZ/ji+AVooq4raTGZqLjguXBiNIZTv7n+GBSK/NJZt7SKTNRzf17vafNkOlEkRaNB",
	"sTrnJf1rpEPfJ62VdqRvXKlD/E9p0yDsRHECV5zBlOzTHuVo5UK1JiDRHnnYInXyuHW0Ves09cUfE/Xi",
	"+Bim1OsHqRgFpmSmjX1f5ByF8LNIW1jsDjbwxAitixcInRIDUfnUHKnV0U8hAO5J12OT7e6txrnbpGXO",
	"1MhfeH7MAPD8+Pj3kckLs3Uz9HWnpuBXE8OHanuGiw9a/jk4+XGTef74/u59x88bxCqt7TKlkN8SoG/Y",
	"A5McHBALS2y4eTx4T6N3kHmP42w2KkIW+EswWqvgaAQ1fAnSwTVi5RPwOEv2cBTZYrenjNdNqRX1lGv0",
	"9krukS+csvDi+EXSXjgIX5PExt0056j8rpkt0HUsLAyWdhaKjj4jSnRoLO/rzu0Xi8eka/jqu6uU82r8",
	"pTQnFw9OYn6kz9kddLZksG1HSUcZf2nRF6ncb26Uu7VGf0qDvESrixtsCwL9NVRP/dMvsEqfof6rWmFg",
	"fdLFAkfnSwQmartGQM9BcEr2hqHCvXZKROdxhhoJEX2rMlkESfwcgiiFnBlB5+lcGut8+KIqhJtrUzYl",
	"DUvJfNdKdpQcR++YHxFFxdzXP0sF0o0Sco2xBYGdAduFHnPBZRMapJn6ND+FLyfqr8eft8+ClJDpuvC3",
	"bDNsp5U/hCB+6E0A+ZSM8MXxi9/eAN9trHHPdvxZ4OAelfoFOEBWmNYxg+YpvhJ5eBb0TXPD01RfxDIg",
	"y8ffRBlO+WYo85TV32cceDJP1I7Fb5YPTn3hztT7ZNSuCSFyySGz9GusHN8rTRShlSOLW8kMieL7l57Z",
	"1mfYvNROtl2IjusS2c7LdvCYkNN6IOQl7JR1Nen+zMLH8IPHk3XsJmQQdeq9vb8Qa7R9AX+rJh6SYLXU",
	"BcKMr3p44ea1RS8UAxGNqjQYvaLHYS12kcULkXbU5bcl/Tt1QI8i+s976jc42Ij57wY4p0/dsD8BEvG8",
	"NouqfgH2hIqaFG/ij588BX8MZihvuGSmg4kS7bNImGiQiQqXGhJtEsNlkVIRpsqFEq422CIZ1/f4Ohof",
	"QmCkmygU2bINuDV3JfzeEg0mvtKKcyxYdxNvbXGsRpQ1yJw75gXwNd2PxcKJ6mc/E0UdzHS+jijHt0gO",
	"QgEQDGOhUWrRSFHIf2A+OunWEFlYoGPwsNid/sbN0GYNt1ti6SfJ8X/RxF7ziXJoXcrV8J1rAYO5yBzm",
	"HIkkif0S7OIqb94zC8NpVRfFh7Ci0wSmVW2X02SipnzX+SHTZYmKn/hcC24j1WI6an4YYdo59ufUHS25",
	"DwhNFHtNnYG9xnUV6mUbGSLonKhOfx+CVU8DoLqlz7oKR84YXmFTpJSHvM8NRaDTqvkYz6vK6Mwnz0Ri",
	"+fz4GKZNT9PEX8usltoioDCFRMOJgWXl/OiyKPgizQeRYSUkx5Od9lzSGUmb1Hb/HKZLLPLpGN40k5Wu",
	"nUmzmI22cIHrRIm5C4YTfkJkyJ21963TER2KvlCXLzxZd1kAmK2bQKbP9ggxQn9tMIYvdU7mWlck+HMO",
	"PcKwMd5QkjdRpbiVZV2Ods8vX2qWbkDOQ/5003/XXof/kfrv01fh23BxwKlmcI1cxMau9hJFzvc4wdne",
	"efNel7uU6htUC7fs1pG21+N7hW3BpCMrV+2NHpbsPKzLU8V6/9uygo1SzT8o9NdTB7mHBbRHw/x+4x52",
	"LHrENCBQmT9A8KvWyjvpRcMNO+ZLrXh/LNQO8Aw9hPip/G5eXrPAnngRqW09pBbU+WZmB7ZHnzz7umAE",
	"4xOqIR9bpcnNChzKycqsGpx8pP9MrezRx2ydFXiR3x21KSppqLbsxIm2PAS+SU173ngAZtvsFuBxCWU7",
	"6R90BMxEds1HUKYrIp6aM11Co/DWRgino7ocmwp98W2Qv4PJ4w9iEYcURC3ffnh3evX1h4tX4caz5uhO",
	"iL2Fm/yYMNATSg1rdi94/p5R0f3pS59sVHQj22Nb/18jubDbWVP+V/y2c6uGW7rT1X2fgRAU3xrcd0ER",
	"Mnb3qbs1mBbSurTN7P2DYvMPUoMzXZYitUgCuhY1fNFtqAMn7jZbR0F+rj07CZKE8tyDBv0a1yvyFn0Z",
	"lPeOfAImpwAckYuSgBGc/zlbk8U6qTKXOjQlNy9EBUNuDCuUiyX/UICuZwWOyIg5NiscPP/rGC6Rdjqd",
	"SWFDKQcHOZyOWS/AP5cWE2ObWPVc+kQ1rsjVCsd7FuDnwW9pxY9KUGtL0x6stfpUzbubRLVt3d+0JXMb",
	"2cDW/wbS5q8TcEJVTJfp2vbV5fng/V3SxBF2TdZnjqZNlfUnYrO/EW/u+amI35k1d8u//pSK6ZcQxIZW",
	"PkEp42ljMpH6MpKNiNdeTW3bD35LHen/vYNHKctnv5ooWyU6PRt4FioAPnGlCZHS+3/p4X514eHMTUQm",
	"LoYaHMUEz6ObzwZ37+/+LwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
