//go:build go1.22

// Package igen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package igen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	PublisherCCScopes publisherCCContextKey = "publisherCC.Scopes"
	TaskJWTScopes     taskJWTContextKey     = "taskJWT.Scopes"
)

// ComponentEndpoint defines model for ComponentEndpoint.
type ComponentEndpoint struct {
	Component string `json:"component"`
	URL       string `json:"url"`
}

// Error Flat error envelope returned by every non-2xx response.
type Error struct {
	// Code Machine-readable error code (stable slug).
	Code string `json:"code"`

	// Details Field-level details for validation errors.
	Details []ErrorDetail `json:"details,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Identity Git commit identity. Field names are CAPITALIZED on the wire (historical lockstep — changing them needs a coordinated runner release). KNOWN GAP: the runner's credhelper currently reads lowercase keys, so its identity-drift rewrite never fires; fix belongs runner-side (case-tolerant parse), not here.
type Identity struct {
	Email string `json:"Email"`
	Login string `json:"Login"`
	Name  string `json:"Name"`
}

// RefreshResponse Fresh GitHub token + commit identity for the execution.
type RefreshResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Identity Git commit identity. Field names are CAPITALIZED on the wire (historical lockstep — changing them needs a coordinated runner release). KNOWN GAP: the runner's credhelper currently reads lowercase keys, so its identity-drift rewrite never fires; fix belongs runner-side (case-tolerant parse), not here.
	Identity Identity `json:"identity"`
	TaskID   string   `json:"taskId"`
	Token    string   `json:"token"`
}

// ValidationContextResponse The deployed endpoints a validation run drives. Generated as igen.ValidationContextResponse (no x-go-type) — igen must stay a leaf, so the edge's internal handler projects the delivery domain's own struct onto this wire shape (the same decoupling as RefreshResponse).
// It carries no oracle path; the runner already knows where the oracle is.
type ValidationContextResponse struct {
	Endpoints []ComponentEndpoint `json:"endpoints"`
}

// publisherCCContextKey is the context key for publisherCC security scheme
type publisherCCContextKey string

// taskJWTContextKey is the context key for taskJWT security scheme
type taskJWTContextKey string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Refresh an execution's git credentials (runner callback)
	// (POST /executions/{executionId}/credentials/refresh)
	RunnerRefreshCredentials(w http.ResponseWriter, r *http.Request, executionID string)
	// Fetch a validation run's deployed endpoints (runner callback)
	// (GET /validation/{cycleId}/context)
	RunnerValidationContext(w http.ResponseWriter, r *http.Request, cycleID string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RunnerRefreshCredentials operation middleware
func (siw *ServerInterfaceWrapper) RunnerRefreshCredentials(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "executionId" -------------
	var executionID string

	err = runtime.BindStyledParameterWithOptions("simple", "executionId", r.PathValue("executionId"), &executionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TaskJWTScopes, []string{})

	ctx = context.WithValue(ctx, PublisherCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunnerRefreshCredentials(w, r, executionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunnerValidationContext operation middleware
func (siw *ServerInterfaceWrapper) RunnerValidationContext(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "cycleId" -------------
	var cycleID string

	err = runtime.BindStyledParameterWithOptions("simple", "cycleId", r.PathValue("cycleId"), &cycleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cycleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TaskJWTScopes, []string{})

	ctx = context.WithValue(ctx, PublisherCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunnerValidationContext(w, r, cycleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/executions/{executionId}/credentials/refresh", wrapper.RunnerRefreshCredentials)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/validation/{cycleId}/context", wrapper.RunnerValidationContext)

	return m
}

type RunnerRefreshCredentialsRequestObject struct {
	ExecutionID string `json:"executionId"`
}

type RunnerRefreshCredentialsResponseObject interface {
	VisitRunnerRefreshCredentialsResponse(w http.ResponseWriter) error
}

type RunnerRefreshCredentials200JSONResponse RefreshResponse

func (response RunnerRefreshCredentials200JSONResponse) VisitRunnerRefreshCredentialsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerRefreshCredentialsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RunnerRefreshCredentialsdefaultJSONResponse) VisitRunnerRefreshCredentialsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerValidationContextRequestObject struct {
	CycleID string `json:"cycleId"`
}

type RunnerValidationContextResponseObject interface {
	VisitRunnerValidationContextResponse(w http.ResponseWriter) error
}

type RunnerValidationContext200JSONResponse ValidationContextResponse

func (response RunnerValidationContext200JSONResponse) VisitRunnerValidationContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerValidationContextdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RunnerValidationContextdefaultJSONResponse) VisitRunnerValidationContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Refresh an execution's git credentials (runner callback)
	// (POST /executions/{executionId}/credentials/refresh)
	RunnerRefreshCredentials(ctx context.Context, request RunnerRefreshCredentialsRequestObject) (RunnerRefreshCredentialsResponseObject, error)
	// Fetch a validation run's deployed endpoints (runner callback)
	// (GET /validation/{cycleId}/context)
	RunnerValidationContext(ctx context.Context, request RunnerValidationContextRequestObject) (RunnerValidationContextResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RunnerRefreshCredentials operation middleware
func (sh *strictHandler) RunnerRefreshCredentials(w http.ResponseWriter, r *http.Request, executionID string) {
	var request RunnerRefreshCredentialsRequestObject

	request.ExecutionID = executionID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunnerRefreshCredentials(ctx, request.(RunnerRefreshCredentialsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunnerRefreshCredentials")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunnerRefreshCredentialsResponseObject); ok {
		if err := validResponse.VisitRunnerRefreshCredentialsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunnerValidationContext operation middleware
func (sh *strictHandler) RunnerValidationContext(w http.ResponseWriter, r *http.Request, cycleID string) {
	var request RunnerValidationContextRequestObject

	request.CycleID = cycleID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunnerValidationContext(ctx, request.(RunnerValidationContextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunnerValidationContext")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunnerValidationContextResponseObject); ok {
		if err := validResponse.VisitRunnerValidationContextResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FjbbiO5Ef2VAhPANqKLZxbJg/bJ65FntTPrMWwnA2RkLEpkqZtrNtlhsWULhoF8RL4wXxIUu3VZSx57",
	"gjwE+6S+kFXFqlOnTutB6VDVwZNPrEYPinVJFebL09WLsTd1sD7JQzTGJhs8uosYaorJEqvRHB1TT9Vb",
	"j7YMy01a1qRGilO0vlCPPdVEt+f5Y09F+kdjIxk1+rJlot1w01ttCLNfSScxNI4xxBdDM8Q62lreq5E6",
	"c5iAZCOQX5ALNUGk1ERPBmZLoAXFJfjg+2/v7yES18EzDdTuEQ3J72+t/4y6tJ76kdDgzFHnSRbDIaf8",
	"iF1THInBncQYSmgd75o9s+RM39GCHHSLYB4iLNBZg7KodcRi1iaqso0/RpqrkfrDcFPnYVfkYU7du2xK",
	"PHehYIy4lPuKmLHYc8Afmwr90+N1q/ecaaeohtTG+rM17QL7NtDNJUl7Abd1mq/H15r4eoATQz7ZtPxG",
	"3L23CXSoKpvAdhYGkOsKHitiwEhwenIxuT75OPn7+B0ED6kkuLOR4LC0nEK0Gh24oG85UQ3//ue/QJfo",
	"C+sLWVqBJzIMCDqEaKzHRAZi4z1FiOQImY4G8OH80+dzeH9yMcr22/cHDDqSKcnVFEE3MZJPbglSaAYX",
	"7ihqZIJbWnIPOIBNvD5H30Q7TxDpLtpE4KWFYG4j8fcwt/cwIxd8wZ2rPltpBjHXT8FRRJ+gxsh01AMf",
	"EpQU9/TbuOoQsVPdj6Gwfu+bc6xeUfS8qtc5WJnbV/lLmkfi8rLjhG8lHtkL7236sZlBCrfk4U9PEZGb",
	"WqpC96Qb2bibCLqvJbUnmVvnIVaY1EgZTNRPNp9kJw92C7JfI4U1tIURkG8n+9spB/9yXttlva2AtyJZ",
	"O9iX6L+tae00+ET36b9M+XVJYKh2YUkGqBtl0iBbvBkbDybaBfEA3pOnmLsGGWxBfvBsJHDoA9z3i9CX",
	"6I9yM8oOqBpOwAmXgOAI57lbcklNQQcM1ieKHh2U6I2jCHUMcm7Oiww5mweQCRVaf8AQ7jxwio1OEHwS",
	"U5ZbUuASa4JD2cZYyV4dmtoJGyDDE7AeDaZ+kkBjjJYYfIAQUTuCGlP5/RYTADpp+iXc+nDHcCfdmF93",
	"6y3vgeQqtXLzqvGzKzB2htATNG187CLmsaeYdBNtWl6Jgzaqupk5yyXF01O5nRFGimerhvnp87XaxUvj",
	"jZSEYj/EAtYWQDtLPvWFIwXA6BhW8M5HkmhaB5v+K1OqV50k3l4Xww9nZ322hagRCUM2w+XV2z//BX76",
	"fA2HXZHqYPjoZeeSGevnYXeOI9V9rO02IJniwmoh5X53CdzEOWoawETapjGWvBYIQNXqHO5NfUv3ghAd",
	"PAdHo6yecu50r5sGBSa6w2UfzUJgw2QGMM5AFxzlBjvgqU9YcB6Heb5odNIgh5f5zD04GcNVaowNPbi6",
	"HB+tO4tr0t2kQkFsmHrZKpeYBnCazUj8qZTiaUwyVlMJCM9WfOqfKzmECAhfLVPbT6iT9cXUi13LgO4O",
	"lwyGhGwMzGOo8rIFRTu3ZGDjaZW1vEaagDhNvfV1kwZTP/WX7aNWM3RcJqRVoPWcWorISUFvYBbMsq+x",
	"rttQNwmf+sM38LP9QVSvoTk2Lh3BjOYhEqBfrgkqNp5bt389Px9fwsdPpx+ursedftjKTz+2nAN0n3VJ",
	"RoqAoqlabZ1KmnodjFBUB+TMm4lXpxyuBDfMlom4ZVMRBZ1BKVtoEqDYeU7kZB1qk5M+OBlfwGSF8Ku3",
	"V3ByMVE9taDIbSO8GRwPjqVNQ00ea6tG6rvB8eA7ITlMZWaS4Xoc8/BhfT0xj8Ot0w+702fqCZzH8zrX",
	"MklVp3+6ddvIys4iVpQoshp9edqt45VPsGabqwXmM9S3kmjWQUqcgoxZ2SThq57yWQSprbDVNrOm2FDH",
	"I7hvpt/I4rYmORdvj4/bzx+fuu87rGsnTWWDH/7KwW++JV+aAk8FVear357804f2wyjD83/muP1w3ONu",
	"9WIzUHI11hT+5eax92SyfLmRHHFTVRiXarRSiYB+o+IOGArR/1tccvikhEdZEhVSfdUSnrqROIaVrtXo",
	"Qa42qmX4oJfaUUZgq0vkxAU9D7rN3v5qxwuY20gfyM5eA73czt2ibpfc1Q6TKFUwlmtMupTFQlKdrXmI",
	"vU6aZCt5T8gq7GR88cv1ydWHXybvOjZrvJGZ1X6CtGNvPYv34L5L1P8N5p/Xtr8L9J9R0uWOwj7gfTr8",
	"dS2Qo4mLFUjzn0dquFItw8Ub9Xjz+J8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
