{{- if not .Values.localSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.openbao.addr | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-reader"
{{- end }}
