{{- if not .Values.localSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aep-platform
spec:
  provider:
    vault:
      server: {{ .Values.openbao.addr | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "openchoreo-secret-writer-role"
          serviceAccountRef:
            name: external-secrets-openbao
            namespace: openbao
{{- end }}
